Repository gardener/dashboard, pull requests merged in 2019-05, with the labels that each got.

#368 Use new slogan
  frontend/src/components/MainNavigation.vue
  frontend/src/layouts/Login.vue
Labels: needs/ok-to-test

#349 Use user to fetch namespace
  .secrets.baseline
  backend/lib/services/members.js
  backend/lib/services/projects.js
  backend/lib/services/shoots.js
  backend/lib/utils/index.js
  backend/test/support/nocks/k8s.js
Labels: needs/ok-to-test

#369 Improve infrastructure colors and logos
  .secrets.baseline
  frontend/public/static/background_azure.svg
  frontend/public/static/background_openstack.svg
  frontend/src/assets/aws-white.svg
  frontend/src/assets/aws.svg
  frontend/src/assets/azure-white.svg
  frontend/src/assets/azure.svg
  frontend/src/assets/gcp-white.svg
  frontend/src/assets/gcp.svg
  frontend/src/assets/openstack-white.svg
  frontend/src/assets/openstack.svg
  frontend/src/components/DisabledSecret.vue
  frontend/src/components/InfrastructureIcon.vue
  frontend/src/components/Secret.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/dialogs/CreateClusterDialog.vue
  frontend/src/dialogs/SecretDialog.vue
  frontend/src/dialogs/SecretDialogAlicloud.vue
  frontend/src/dialogs/SecretDialogAws.vue
  frontend/src/dialogs/SecretDialogAzure.vue
  frontend/src/dialogs/SecretDialogGcp.vue
  frontend/src/dialogs/SecretDialogOpenstack.vue
  frontend/src/pages/Secrets.vue
  frontend/src/stylus/main.styl
  frontend/src/utils/index.js
Labels: needs/ok-to-test

#370 Support regions without dedicated seed
  .secrets.baseline
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/src/dialogs/CreateClusterDialog.vue
  frontend/src/store/index.js
Labels: needs/ok-to-test

#371 Update node.js to v10.15.3 and alpine to v3.9
  .dockerignore
  Dockerfile
  backend/.eslintrc.js
  backend/package-lock.json
  backend/package.json
  backend/test/acceptance.spec.js
  backend/test/acceptance/api.cloudprofiles.spec.js
  backend/test/acceptance/api.domains.spec.js
  backend/test/acceptance/api.info.spec.js
  backend/test/acceptance/api.infrastructureSecrets.spec.js
  backend/test/acceptance/api.members.spec.js
  backend/test/acceptance/api.projects.spec.js
  backend/test/acceptance/api.shoots.spec.js
  backend/test/acceptance/api.user.spec.js
  backend/test/acceptance/auth.spec.js
  backend/test/acceptance/healthz.spec.js
  backend/test/acceptance/security.spec.js
  backend/test/acceptance/webhook.spec.js
  backend/test/dockerfile.spec.js
  backend/test/support/index.js
  backend/test/support/nocks/index.js
Labels: needs/ok-to-test

#374 [MASTER] [FIX] Regions without seed for azure
  backend/lib/services/cloudprofiles.js
  frontend/src/store/index.js
Labels: needs/ok-to-test, reviewed/ok-to-test

#375 [HOTFIX] [FIX] Regions without seed for azure
  backend/lib/services/cloudprofiles.js
  frontend/src/store/index.js
Labels: needs/ok-to-test

#376 [HOTFIX]Fix extra newline generated from 'toyaml' function
  charts/gardener-dashboard/templates/configmap.yaml
Labels: needs/ok-to-test

#373 [MASTER]Fix extra newline generated from 'toyaml' function
  charts/gardener-dashboard/templates/configmap.yaml
Labels: needs/ok-to-test

#378 [HOTFIX] Fix infra sorting
  frontend/src/store/modules/shoots.js
Labels: reviewed/ok-to-test

#377 [MASTER] Fix infra sorting
  frontend/src/store/modules/shoots.js
Labels: needs/ok-to-test

#379 [HOTFIX] Changed countUpdateDomains to countFaultDomains
  backend/lib/services/cloudprofiles.js
  frontend/src/store/index.js
Labels: needs/ok-to-test

#380 [MASTER] Changed countUpdateDomains to countFaultDomains
  backend/lib/services/cloudprofiles.js
  frontend/src/store/index.js
Labels: needs/ok-to-test

#385 Fixed delete the hibernation start / hibernation end time
  frontend/src/components/HibernationScheduleEvent.vue
Labels: needs/ok-to-test

#388 Dedeprecate nginx ingress-controller for now
  frontend/src/components/ShootAddonsCard.vue
  frontend/src/dialogs/CreateClusterDialog.vue
Labels: component/dashboard, kind/task, needs/ok-to-test, topology/shoot

#391 keep all values when saving a worker group
  frontend/src/components/ManageWorkers.vue
Labels: needs/ok-to-test

#392 Fixes for 1.31.2
  frontend/src/components/HibernationScheduleEvent.vue
  frontend/src/components/ManageWorkers.vue
  frontend/src/components/ShootAddonsCard.vue
  frontend/src/dialogs/CreateClusterDialog.vue
Labels: needs/ok-to-test

#394 Do not sanitize/filter shoot yaml
  backend/lib/services/shoots.js
  backend/package-lock.json
  backend/package.json
  backend/test/acceptance/api.shoots.spec.js
Labels: needs/ok-to-test
