Repository gardener/dashboard, pull requests merged in 2020-10, with the labels that each got.

#817 [hotfix-1.46] Fix: project creation not possible
  frontend/src/router/routes.js
Labels: needs/ok-to-test, reviewed/lgtm

#818 [master] Fix: project creation not possible
  frontend/src/router/routes.js
Labels: needs/ok-to-test, reviewed/lgtm

#820 [hotfix-1.46] Return 404 Not Found for not existing static assets #819
  backend/lib/app.js
Labels: needs/ok-to-test, reviewed/lgtm

#829 Fix storage plugin not returning item
  frontend/src/plugins/storage.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#830 Fix broken splitpanes
  frontend/src/components/GSplitpane.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#823 Force future date for expiration / deletion dates
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/SelfTerminationWarning.vue
  frontend/src/components/ShootDetails/ShootDetailsCard.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootMessageDetails.vue
  frontend/src/components/ShootTickets/Ticket.vue
  frontend/src/components/ShootTickets/TicketComment.vue
  frontend/src/components/StaleProjectWarning.vue
  frontend/src/components/TerminalSettings.vue
  frontend/src/components/TimeString.vue
  frontend/src/components/VersionExpirationWarning.vue
  frontend/src/views/Administration.vue
Labels: needs/ok-to-test, reviewed/lgtm

#827 Automatically select region without seed
  frontend/src/store/modules/shoots.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#825 Ticket usability improvements
  charts/__tests__/gardener-dashboard.spec.js
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootTickets/Ticket.vue
  frontend/src/components/ShootTickets/TicketComment.vue
  frontend/src/components/ShootTickets/TicketLabel.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#832 Use Yarn 2 in pipeline jobs and callbacks
  .ci/bump_version
  .ci/check
  .ci/pipeline_definitions
  .ci/prepare_release
  .dockerignore
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/releases/yarn-2.3.3.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  Dockerfile
  backend/bin/sync-version
  backend/package.json
  yarn.lock
Labels: needs/ok-to-test, needs/second-opinion, size/l

#837 Fix action button not being disabled when cluster is in deletion
  frontend/src/mixins/shootItem.js
  frontend/src/utils/index.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#839 Fix terminal runtime selection
  frontend/src/components/GTerminal.vue
  frontend/src/components/TerminalSettings.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#840 Update checkmarx configuration
  backend/srcclr.yml
  frontend/srcclr.yml
  srcclr.yml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#841 Checkmarx config for each package
  backend/srcclr.yml
  charts/srcclr.yml
  frontend/srcclr.yml
  packages/kube-client/srcclr.yml
  packages/kube-config/srcclr.yml
  packages/logger/srcclr.yml
  packages/request/srcclr.yml
  srcclr.yml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#843 Fix unreachable seed check
  backend/lib/services/seeds.js
Labels: needs/ok-to-test, size/xs

#845 Support async components
  backend/srcclr.yml
  charts/srcclr.yml
  frontend/src/components/NewShoot/NewShootDetails.vue
  frontend/src/components/PurposeConfiguration.vue
  frontend/src/components/ShootHibernation/HibernationConfiguration.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/mixins/asyncRef.js
  frontend/src/mixins/shootItem.js
  frontend/src/views/NewShoot.vue
  frontend/src/views/NewShootEditor.vue
  frontend/src/views/ShootItemEditor.vue
  frontend/srcclr.yml
  packages/kube-client/srcclr.yml
  packages/kube-config/srcclr.yml
  packages/logger/srcclr.yml
  packages/request/srcclr.yml
  srcclr.yml
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#846 Fix multiline strings in chart
  charts/gardener-dashboard/templates/configmap.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#847 Confirm dialog using "enter" key press
  frontend/src/components/dialogs/GDialog.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#844 Adapt chart to include unreachableSeeds config
  charts/__tests__/gardener-dashboard.spec.js
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#822 Handling for duplicate worker zones
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#821 Member Management Improvements
  backend/lib/services/members.js
  backend/lib/utils/index.js
  backend/test/acceptance/api.members.spec.js
  backend/test/services.members.spec.js
  backend/test/support/nocks/k8s.js
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/ProjectUserRow.vue
  frontend/src/components/SecretRow.vue
  frontend/src/components/dialogs/ConfirmDialog.vue
  frontend/src/components/dialogs/MemberDialog.vue
  frontend/src/components/dialogs/ProjectDialog.vue
  frontend/src/utils/index.js
  frontend/src/views/Administration.vue
  frontend/src/views/Members.vue
Labels: needs/changes, needs/ok-to-test, size/xl

#850 Update yarn2 plugins
  .pnp.js
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-production-install.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarnrc.yml
  Dockerfile
  Makefile
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#851 Fixed subcomponent validation state reset
  frontend/src/components/NewShoot/NewShootInfrastructureDetails.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#853 Minor enhancements to members management
  backend/lib/services/members.js
  backend/lib/services/members/Member.js
  backend/lib/services/members/MemberManager.js
  backend/lib/services/members/SubjectList.js
  backend/lib/services/members/SubjectListItem.js
  backend/lib/services/members/index.js
  backend/test/acceptance/api.members.spec.js
  backend/test/services.members.spec.js
  backend/test/support/nocks/k8s.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xl
