Repository gardener/dashboard, pull requests merged in 2020-12, with the labels that each got.

#897 Honor insecureSkipTLSVerify spec from gardener-apiserver
  backend/lib/routes/info.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#890 Add support for custom shoot fields
  frontend/src/components/ShootCustomField.vue
  frontend/src/components/ShootDetails/CustomFieldsCard.vue
  frontend/src/components/ShootDetails/ShootDetails.vue
  frontend/src/components/ShootDetails/ShootDetailsCard.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootWorkers/WorkerGroup.vue
  frontend/src/plugins/storage.js
  frontend/src/router/guards.js
  frontend/src/store/index.js
  frontend/src/store/modules/shoots.js
  frontend/src/views/Administration.vue
  frontend/src/views/NewShootEditor.vue
  frontend/src/views/ShootItemEditor.vue
  frontend/src/views/ShootList.vue
  frontend/tests/unit/store.index.spec.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#901 Remove footer logo
  frontend/public/static/sap-logo.svg
  frontend/src/components/MainNavigation.vue
  frontend/src/views/Login.vue
  frontend/tests/unit/MainNavigation.spec.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#902 Fix markdown converter initialization if no gitHub.apiUrl is configured
  backend/lib/services/tickets.js
Labels: reviewed/lgtm, size/xs

#904 Update dex to v2.27.0
  charts/identity/values.yaml
Labels: needs/changes, needs/ok-to-test, size/xs

#907 Update highlight.js to version 10.4.1
  .pnp.js
  .yarn/cache/highlight.js-npm-10.4.1-7888d5927d-067a8cc822.zip
  frontend/package.json
  frontend/src/components/CodeBlock.vue
  yarn.lock
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#909 EditableText should not allow to save if an error exists
  frontend/src/components/editable/EditableText.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#899 Permanently hide alert banner
  charts/__tests__/gardener-dashboard.spec.js
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/src/components/GAlert.vue
  frontend/src/components/GMessage.vue
  frontend/src/components/MainContent.vue
  frontend/src/components/ShootEditor.vue
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/MemberDialog.vue
  frontend/src/components/dialogs/ProjectDialog.vue
  frontend/src/components/dialogs/SecretDialog.vue
  frontend/src/components/dialogs/SecretDialogDelete.vue
  frontend/src/components/dialogs/WebterminalServiceAccountDialog.vue
  frontend/src/sass/main.scss
  frontend/src/store/index.js
  frontend/src/views/NewShoot.vue
  frontend/src/views/NewShootEditor.vue
  frontend/src/views/ShootItemEditor.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#881 ControllerRegistration support / List Networking Types
  backend/__fixtures__/controllerregistrations.js
  backend/__fixtures__/index.js
  backend/jest.setup.js
  backend/lib/cache/index.js
  backend/lib/routes/gardenerExtensions.js
  backend/lib/routes/index.js
  backend/lib/routes/info.js
  backend/lib/routes/networkingTypes.js
  backend/lib/services/authorization.js
  backend/lib/services/controllerregistrations.js
  backend/lib/services/index.js
  backend/test/acceptance/__snapshots__/api.cloudprofiles.spec.js.snap
  backend/test/acceptance/__snapshots__/api.controllerregistrations.spec.js.snap
  backend/test/acceptance/__snapshots__/api.infrastructureSecrets.spec.js.snap
  backend/test/acceptance/api.controllerregistrations.spec.js
  backend/test/cache.spec.js
  backend/test/support/common.js
  frontend/src/components/MainToolbar.vue
  frontend/src/components/NewShoot/NewShootInfrastructureDetails.vue
  frontend/src/router/guards.js
  frontend/src/store/index.js
  frontend/src/store/modules/gardenerExtensions.js
  frontend/src/store/modules/networkingTypes.js
  frontend/src/store/modules/shoots.js
  frontend/src/utils/api.js
  frontend/src/views/NewShoot.vue
  packages/kube-client/lib/resources/GardenerCore.js
Labels: needs/changes, needs/ok-to-test, size/xl

#911 Hide alert banner if no alert message is set
  frontend/src/components/GAlert.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#912 Do not directly set innerHTML of html elements
  frontend/src/utils/shootEditorCompletions.js
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#913 Improve mock implementations
  backend/__fixtures__/auth.js
  backend/__fixtures__/nodes.js
  backend/__fixtures__/projects.js
  backend/__fixtures__/secretbindings.js
  backend/__fixtures__/secrets.js
  backend/__fixtures__/serviceaccounts.js
  backend/__fixtures__/shoots.js
  backend/__fixtures__/terminals.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#914 Orphaned Robot Members
  backend/lib/services/members/Member.js
  backend/lib/services/members/MemberManager.js
  backend/lib/services/members/SubjectList.js
  backend/test/acceptance/__snapshots__/api.members.spec.js.snap
  backend/test/services.members.spec.js
  frontend/src/components/ProjectServiceAccountRow.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/m

#872 Member Management Part2
  backend/lib/routes/members.js
  backend/lib/routes/terminals.js
  backend/lib/services/members/Member.js
  backend/lib/services/members/MemberManager.js
  backend/lib/services/members/SubjectList.js
  backend/lib/services/members/index.js
  backend/test/acceptance/__snapshots__/api.members.spec.js.snap
  backend/test/acceptance/api.members.spec.js
  backend/test/services.members.spec.js
  frontend/src/components/MemberAccountRoles.vue
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/ProjectUserRow.vue
  frontend/src/components/TableColumnSelection.vue
  frontend/src/components/dialogs/MemberHelpDialog.vue
  frontend/src/components/dialogs/WebterminalServiceAccountDialog.vue
  frontend/src/components/messages/RemoveProjectMember.vue
  frontend/src/components/messages/RotateServiceAccountSecret.vue
  frontend/src/store/index.js
  frontend/src/store/modules/members.js
  frontend/src/utils/api.js
  frontend/src/utils/index.js
  frontend/src/views/Members.vue
  frontend/src/views/ShootList.vue
Labels: needs/changes, needs/ok-to-test, size/xl

#916 Changed member help texts
  frontend/src/components/dialogs/MemberHelpDialog.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#917 Fixed some small issues introduced with last PRs
  frontend/src/components/MainToolbar.vue
  frontend/src/components/ShootDetails/CustomFieldsCard.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#920 Fixed some (other) small issues introduced with last PRs
  frontend/src/components/NewShoot/NewShootInfrastructureDetails.vue
  frontend/src/components/messages/RemoveProjectMember.vue
  frontend/src/router/guards.js
  frontend/src/store/modules/shoots.js
  frontend/src/views/Members.vue
  frontend/src/views/NewShoot.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#925 Delete folder `backend/test/support`
  backend/test/support/common.js
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#926 Fixed api.info acceptance test
  backend/test/acceptance/__snapshots__/api.info.spec.js.snap
  backend/test/acceptance/api.info.spec.js
Labels: needs/ok-to-test, needs/review, size/xs

#922 Fixed Control Plane Migration Indication
  frontend/src/components/ShootSeedName.vue
  frontend/src/mixins/shootItem.js
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#928 Improve wording in shoot action tooltip
  frontend/src/mixins/shootItem.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
