Repository gardener/dashboard, pull requests merged in 2020-04, with the labels that each got.

#652 Do not accept values other than ^(\d+)Gi$
  frontend/src/utils/index.js
Labels: needs/ok-to-test, reviewed/ok-to-test

#641 Kubernetes Client Cache
  LICENSE.md
  backend/.nycrc
  backend/lib/api.js
  backend/lib/app.js
  backend/lib/cache/index.js
  backend/lib/github/octokit.js
  backend/lib/io.js
  backend/lib/kubernetes-client/ApiErrors.js
  backend/lib/kubernetes-client/Client.js
  backend/lib/kubernetes-client/HttpClient.js
  backend/lib/kubernetes-client/cache/ListPager.js
  backend/lib/kubernetes-client/cache/Reflector.js
  backend/lib/kubernetes-client/cache/Store.js
  backend/lib/kubernetes-client/cache/index.js
  backend/lib/kubernetes-client/debug.js
  backend/lib/kubernetes-client/groups.js
  backend/lib/kubernetes-client/index.js
  backend/lib/kubernetes-client/mixins.js
  backend/lib/kubernetes-client/resources/GardenerCore.js
  backend/lib/kubernetes-client/resources/index.js
  backend/lib/kubernetes-client/symbols.js
  backend/lib/logger/Logger.js
  backend/lib/middleware.js
  backend/lib/security.js
  backend/lib/server.js
  backend/lib/services/infrastructureSecrets.js
  backend/lib/services/members.js
  backend/lib/services/projects.js
  backend/lib/watches/common.js
  backend/lib/watches/index.js
  backend/lib/watches/journals.js
  backend/lib/watches/quotas.js
  backend/lib/watches/seeds.js
  backend/lib/watches/shoots.js
  backend/package.json
  backend/test/acceptance/api.infrastructureSecrets.spec.js
  backend/test/acceptance/api.members.spec.js
  backend/test/acceptance/api.projects.spec.js
  backend/test/cache.spec.js
  backend/test/kubernetes-client.api-errors.spec.js
  backend/test/kubernetes-client.cache.spec.js
  backend/test/kubernetes-client.client.spec.js
  backend/test/kubernetes-client.debug.spec.js
  backend/test/kubernetes-client.http-client.spec.js
  backend/test/kubernetes-client.mixins.spec.js
  backend/test/kubernetes-client.spec.js
  backend/test/kubernetes-client.watch-builder.spec.js
  backend/test/logger.spec.js
  backend/test/server.spec.js
  backend/test/support/common.js
  backend/test/support/nocks/k8s.js
  backend/test/watches.spec.js
  backend/yarn.lock
Labels: needs/ok-to-test, reviewed/ok-to-test

#655 renamed Tenant Name to Project / Tenant name
  frontend/src/dialogs/SecretDialogOpenstack.vue
Labels: needs/ok-to-test

#654 add namespace to create shoot resource
  frontend/src/store/modules/shoots.js
Labels: needs/ok-to-test

#659 Update the Shoot status label
  backend/lib/services/shoots.js
  backend/lib/utils/index.js
  backend/test/utils.spec.js
  backend/test/watches.spec.js
  frontend/src/utils/index.js
Labels: needs/ok-to-test

#661 Fixed volume size input
  frontend/src/components/ShootWorkers/VolumeSizeInput.vue
Labels: needs/ok-to-test

#660 Optimized Create Cluster / Cluster Editor Dialogs Buttons
  frontend/src/pages/NewShoot.vue
  frontend/src/pages/ShootDetailsEditor.vue
Labels: needs/ok-to-test

#657 Add gardenctl commands
  backend/lib/config/gardener.js
  backend/lib/services/members.js
  backend/test/config.spec.js
  frontend/src/components/ShootDetails/GardenctlCard.vue
  frontend/src/pages/ShootDetails.vue
Labels: needs/ok-to-test

#664 Remove old data property
  frontend/src/pages/Account.vue
Labels: needs/ok-to-test

#663 Rename suse-jeos to suse-chost
  frontend/src/components/VendorIcon.vue
  frontend/src/store/index.js
  frontend/tests/unit/store.index.spec.js
Labels: needs/ok-to-test

#665 [vuetify-2.2] style markdown links
  frontend/src/components/ExternalLink.vue
  frontend/src/utils/index.js
Labels: reviewed/ok-to-test

#667 Filter floating pools that start or end with wildcard
  frontend/src/store/index.js
Labels: needs/ok-to-test

#668 [vuetify-2.2] Filter floating pools that start or end with wildcard
  frontend/src/store/index.js
Labels: reviewed/ok-to-test

#669 Use gardener logo for gardenlinux os image
  frontend/src/components/VendorIcon.vue
  frontend/src/store/index.js
Labels: needs/ok-to-test

#666 [vuetify-2.2] Rename suse-jeos to suse-chost
  frontend/src/components/VendorIcon.vue
  frontend/src/store/index.js
  frontend/tests/unit/store.index.spec.js
Labels: reviewed/lgtm, reviewed/ok-to-test

#670 [vuetify-2.2] Use gardener logo for gardenlinux os image
  frontend/src/components/VendorIcon.vue
  frontend/src/store/index.js
Labels: reviewed/ok-to-test

#672 Always v-slot instead slot and slot-scope
  frontend/src/components/DeleteCluster.vue
  frontend/src/components/GPopper.vue
  frontend/src/components/GTerminal.vue
  frontend/src/components/NewShoot/NewShootInfrastructureDetails.vue
  frontend/src/components/PurposeConfiguration.vue
  frontend/src/components/ReconcileStart.vue
  frontend/src/components/RotateKubeconfigStart.vue
  frontend/src/components/Secret.vue
  frontend/src/components/ShootAddons/AddonConfiguration.vue
  frontend/src/components/ShootHibernation/ChangeHibernation.vue
  frontend/src/components/ShootHibernation/HibernationConfiguration.vue
  frontend/src/components/ShootHibernation/HibernationScheduleWarning.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootMaintenance/MaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/MaintenanceStart.vue
  frontend/src/components/ShootStatus.vue
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/components/ShootWorkers/WorkerGroup.vue
  frontend/src/components/StatusTag.vue
  frontend/src/components/dialogs/ConfirmDialog.vue
  frontend/src/components/dialogs/SecretDialogAlicloud.vue
  frontend/src/components/dialogs/SecretDialogAlicloudHelp.vue
  frontend/src/components/dialogs/SecretDialogAws.vue
  frontend/src/components/dialogs/SecretDialogAwsHelp.vue
  frontend/src/components/dialogs/SecretDialogAzure.vue
  frontend/src/components/dialogs/SecretDialogAzureHelp.vue
  frontend/src/components/dialogs/SecretDialogDelete.vue
  frontend/src/components/dialogs/SecretDialogGcp.vue
  frontend/src/components/dialogs/SecretDialogGcpHelp.vue
  frontend/src/components/dialogs/SecretDialogMetal.vue
  frontend/src/components/dialogs/SecretDialogMetalHelp.vue
  frontend/src/components/dialogs/SecretDialogOpenstack.vue
  frontend/src/components/dialogs/SecretDialogOpenstackHelp.vue
  frontend/src/components/dialogs/SecretDialogVSphere.vue
  frontend/src/components/dialogs/SecretDialogVSphereHelp.vue
  frontend/src/components/dialogs/TargetSelectionDialog.vue
  frontend/src/components/dialogs/TerminalSettingsDialog.vue
  frontend/src/views/Administration.vue
  frontend/src/views/Secrets.vue
Labels: needs/ok-to-test

#676 Change copy button success behaviour
  frontend/src/components/CopyBtn.vue
Labels: needs/ok-to-test

#674 Fix table sorting
  frontend/src/store/index.js
  frontend/src/store/modules/shoots.js
  frontend/src/views/ShootList.vue
  frontend/tests/unit/store.shoots.spec.js
Labels: needs/ok-to-test

#673 Condense gardenctl commands layout
  frontend/src/components/ShootDetails/GardenctlCommands.vue
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/components/UsernamePasswordListTile.vue
  frontend/src/components/dialogs/SecretDialogAlicloud.vue
  frontend/src/components/dialogs/SecretDialogAws.vue
  frontend/src/components/dialogs/SecretDialogAzure.vue
  frontend/src/components/dialogs/SecretDialogMetal.vue
  frontend/src/components/dialogs/SecretDialogOpenstack.vue
  frontend/src/components/dialogs/SecretDialogVSphere.vue
  frontend/src/views/ShootDetails.vue
Labels: needs/ok-to-test

#675 Condense provider, region and zone
  frontend/src/components/CopyBtn.vue
  frontend/src/components/GPopper.vue
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/ShootDetails/ShootInfrastructureCard.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootWorkers/WorkerGroup.vue
  frontend/src/components/Vendor.vue
Labels: needs/ok-to-test

#678 Add more user error codes
  frontend/src/components/ShootStatus.vue
  frontend/src/utils/index.js
Labels: needs/ok-to-test

#682 Fix #679
  frontend/src/components/dialogs/GDialog.vue
Labels: needs/ok-to-test

#680 Terminal: reload not working in edge case
  backend/lib/services/terminals/index.js
  backend/test/acceptance/api.terminals.spec.js
  backend/test/support/nocks/k8s.js
  frontend/src/components/GTerminal.vue
Labels: needs/ok-to-test
