Repository gardener/dashboard, pull requests merged in 2021-11, with the labels that each got.

#1128 [master] Fixed dayjs unit tests
  frontend/tests/unit/utils.moment.spec.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1129 [hotfix-1.52] Fixed dayjs unit tests
  frontend/tests/unit/utils.moment.spec.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1131 [master] Upgrade @octokit/rest to v18.12.0
  .pnp.js
  .yarn/cache/@octokit-core-npm-3.4.0-0e242eba8e-bb8ba9be2c.zip
  .yarn/cache/@octokit-core-npm-3.5.1-a933dedcf7-2967d97b43.zip
  .yarn/cache/@octokit-openapi-types-npm-11.2.0-10b7a5c509-8fc9390afc.zip
  .yarn/cache/@octokit-plugin-paginate-rest-npm-1.1.2-b0b3e646dc-3a60026e4c.zip
  .yarn/cache/@octokit-plugin-paginate-rest-npm-2.17.0-4d48903092-83df8234fb.zip
  .yarn/cache/@octokit-plugin-request-log-npm-1.0.0-b6c4a34e91-fa9e3bd25f.zip
  .yarn/cache/@octokit-plugin-request-log-npm-1.0.4-9ab5a2f888-1b2961de14.zip
  .yarn/cache/@octokit-plugin-rest-endpoint-methods-npm-2.4.0-c786d75f5b-5b4673449f.zip
  .yarn/cache/@octokit-plugin-rest-endpoint-methods-npm-5.13.0-976c113da3-65c1ebb25c.zip
  .yarn/cache/@octokit-request-error-npm-1.2.1-0af51a468f-8612f7a037.zip
  .yarn/cache/@octokit-request-error-npm-2.1.0-51ac624306-0fdf0075bc.zip
  .yarn/cache/@octokit-request-npm-5.6.2-2a9866bd05-f3d45f4922.zip
  .yarn/cache/@octokit-rest-npm-16.43.2-dd2de884c3-d7a7a7cf5a.zip
  .yarn/cache/@octokit-rest-npm-18.12.0-f250ac8e5e-abea3de75f.zip
  .yarn/cache/@octokit-types-npm-2.16.2-67cc6da7f2-0cdd051034.zip
  .yarn/cache/@octokit-types-npm-6.34.0-1de469b7ee-d797eb0d3c.zip
  .yarn/cache/atob-lite-npm-2.0.0-62802899eb-bb739d5e65.zip
  .yarn/cache/btoa-lite-npm-1.0.0-e85ee9286e-d41fc7dc9f.zip
  .yarn/cache/lodash.set-npm-4.3.2-7586c942c2-4dfedacae1.zip
  .yarn/cache/macos-release-npm-2.4.1-4856441ab1-0d15f4b163.zip
  .yarn/cache/octokit-pagination-methods-npm-1.1.0-ce2bd023d6-c3b42406a1.zip
  .yarn/cache/os-name-npm-3.1.0-b5e3fb36cd-b4e5d61010.zip
  .yarn/cache/universal-user-agent-npm-4.0.1-d1d67caaeb-553ee1f53f.zip
  .yarn/cache/windows-release-npm-3.3.3-51824464bb-87a218d7e1.zip
  .yarnrc.yml
  backend/lib/github/octokit.js
  backend/package.json
  yarn.lock
Labels: reviewed/lgtm, size/l, needs/ok-to-test

#1130 [hotfix-1.52] Upgrade @octokit/rest to v18.12.0
  .pnp.js
  .yarn/cache/@octokit-core-npm-3.4.0-0e242eba8e-bb8ba9be2c.zip
  .yarn/cache/@octokit-core-npm-3.5.1-a933dedcf7-2967d97b43.zip
  .yarn/cache/@octokit-openapi-types-npm-11.2.0-10b7a5c509-8fc9390afc.zip
  .yarn/cache/@octokit-plugin-paginate-rest-npm-1.1.2-b0b3e646dc-3a60026e4c.zip
  .yarn/cache/@octokit-plugin-paginate-rest-npm-2.17.0-4d48903092-83df8234fb.zip
  .yarn/cache/@octokit-plugin-request-log-npm-1.0.0-b6c4a34e91-fa9e3bd25f.zip
  .yarn/cache/@octokit-plugin-request-log-npm-1.0.4-9ab5a2f888-1b2961de14.zip
  .yarn/cache/@octokit-plugin-rest-endpoint-methods-npm-2.4.0-c786d75f5b-5b4673449f.zip
  .yarn/cache/@octokit-plugin-rest-endpoint-methods-npm-5.13.0-976c113da3-65c1ebb25c.zip
  .yarn/cache/@octokit-request-error-npm-1.2.1-0af51a468f-8612f7a037.zip
  .yarn/cache/@octokit-request-error-npm-2.1.0-51ac624306-0fdf0075bc.zip
  .yarn/cache/@octokit-request-npm-5.6.2-2a9866bd05-f3d45f4922.zip
  .yarn/cache/@octokit-rest-npm-16.43.2-dd2de884c3-d7a7a7cf5a.zip
  .yarn/cache/@octokit-rest-npm-18.12.0-f250ac8e5e-abea3de75f.zip
  .yarn/cache/@octokit-types-npm-2.16.2-67cc6da7f2-0cdd051034.zip
  .yarn/cache/@octokit-types-npm-6.34.0-1de469b7ee-d797eb0d3c.zip
  .yarn/cache/atob-lite-npm-2.0.0-62802899eb-bb739d5e65.zip
  .yarn/cache/btoa-lite-npm-1.0.0-e85ee9286e-d41fc7dc9f.zip
  .yarn/cache/lodash.set-npm-4.3.2-7586c942c2-4dfedacae1.zip
  .yarn/cache/macos-release-npm-2.4.1-4856441ab1-0d15f4b163.zip
  .yarn/cache/octokit-pagination-methods-npm-1.1.0-ce2bd023d6-c3b42406a1.zip
  .yarn/cache/os-name-npm-3.1.0-b5e3fb36cd-b4e5d61010.zip
  .yarn/cache/universal-user-agent-npm-4.0.1-d1d67caaeb-553ee1f53f.zip
  .yarn/cache/windows-release-npm-3.3.3-51824464bb-87a218d7e1.zip
  .yarnrc.yml
  backend/lib/github/octokit.js
  backend/package.json
  yarn.lock
Labels: reviewed/lgtm, size/l, needs/ok-to-test

#1127 Clarify behaviour after Secret change in dialogue
  frontend/src/components/dialogs/SecretDialog.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test, merge/squash

#1132 Fixed broken links
  docs/concepts/webterminals.md
  docs/usage/project-operations.md
  docs/usage/working-with-service-accounts.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1133 Add missing "zone" to "ControlPlaneConfig"
  frontend/src/utils/createShoot.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1135 [hotfix-1.52] Add missing "zone" to "ControlPlaneConfig" for "hcloud"
  frontend/src/utils/createShoot.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1134 [hotfix-1.52] Clarify behaviour after Secret change in dialog
  frontend/src/components/dialogs/SecretDialog.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1137 [hotfix-1.52] Support search for gardener error codes
  frontend/src/store/modules/shoots/getters.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1138 [master] Support search for gardener error codes
  frontend/src/store/modules/shoots/getters.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
