Repository gardener/dashboard, pull requests merged in 2021-01, with the labels that each got.

#924 update privilege of alicloud secret
  frontend/src/components/dialogs/SecretDialogAlicloudHelp.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#934 [hotfix-1.48]Terminal bootstrapping: Support managed ingress for seeds
  backend/lib/cache/index.js
  backend/lib/services/shoots.js
  backend/lib/services/terminals/terminalBootstrap.js
  backend/lib/services/terminals/utils.js
  backend/lib/utils/index.js
  backend/lib/watches/seeds.js
  backend/test/acceptance/__snapshots__/api.info.spec.js.snap
  backend/test/acceptance/api.info.spec.js
  backend/test/cache.spec.js
  backend/test/services.terminals.spec.js
  backend/test/watches.spec.js
Labels: needs/ok-to-test, needs/second-opinion, size/xl

#930 [master]Terminal bootstrapping: Support managed ingress for seeds
  backend/lib/cache/index.js
  backend/lib/services/shoots.js
  backend/lib/services/terminals/terminalBootstrap.js
  backend/lib/services/terminals/utils.js
  backend/lib/utils/index.js
  backend/lib/watches/seeds.js
  backend/test/cache.spec.js
  backend/test/services.terminals.spec.js
  backend/test/watches.spec.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#936 Use kebab case for custom html events
  frontend/src/components/CodeBlock.vue
  frontend/src/components/CopyBtn.vue
  frontend/src/components/GMessage.vue
  frontend/src/components/NewShoot/NewShootSelectInfrastructure.vue
  frontend/src/components/PositionalDropzone.vue
  frontend/src/components/Purpose.vue
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/components/ShootDetails/ShootDetails.vue
  frontend/src/components/ShootDetails/ShootDetailsCard.vue
  frontend/src/components/ShootDetails/TerminalShortcutsTile.vue
  frontend/src/components/ShootEditor.vue
  frontend/src/components/ShootHibernation/HibernationScheduleEvent.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/ShootVersion/ShootVersionUpdate.vue
  frontend/src/components/ShootWorkers/MachineImage.vue
  frontend/src/components/ShootWorkers/MachineType.vue
  frontend/src/components/ShootWorkers/VolumeType.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
  frontend/src/components/TableColumnSelection.vue
  frontend/src/components/TerminalSettings.vue
  frontend/src/components/TerminalShortcut.vue
  frontend/src/components/TerminalShortcuts.vue
  frontend/src/components/TimeString.vue
  frontend/src/components/dialogs/ActionButtonDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/MemberDialog.vue
  frontend/src/components/dialogs/ProjectDialog.vue
  frontend/src/components/dialogs/SecretDialog.vue
  frontend/src/components/dialogs/SecretDialogDelete.vue
  frontend/src/components/dialogs/SecretDialogWrapper.vue
  frontend/src/components/dialogs/WebterminalServiceAccountDialog.vue
  frontend/src/components/icons/IconBase.vue
  frontend/src/views/Administration.vue
  frontend/src/views/NewShoot.vue
  frontend/src/views/NewShootEditor.vue
  frontend/src/views/ShootItemEditor.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#918 Evaluate MaintenancePreconditionsSatisfied constraint
  frontend/src/components/ConstraintWarning.vue
  frontend/src/components/ShootDetails/ShootLifecycleCard.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootMaintenance/MaintenanceStart.vue
  frontend/src/mixins/shootItem.js
Labels: needs/ok-to-test, needs/rebase, reviewed/ok-to-test, size/m

#933 more permissions required for RAM
  frontend/src/components/dialogs/SecretDialogAlicloudHelp.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#939 Replace axios with Fetch API
  .pnp.js
  .yarn/cache/axios-npm-0.19.2-e4e8599895-bad346deea.zip
  frontend/package.json
  frontend/src/utils/api.js
  yarn.lock
Labels: needs/ok-to-test, reviewed/lgtm, size/s
