Repository gardener/dashboard, pull requests merged in 2021-02, with the labels that each got.

#927 Allow to set volume size if storage type is not fixed
  frontend/src/components/NewShoot/NewShootInfrastructureDetails.vue
  frontend/src/components/ShootWorkers/MachineType.vue
  frontend/src/components/ShootWorkers/VolumeSizeInput.vue
  frontend/src/components/ShootWorkers/WorkerGroup.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
  frontend/src/components/VendorIcon.vue
  frontend/src/utils/index.js
  frontend/src/utils/validators.js
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#943 Show monitoring credentials for project viewer
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  frontend/src/components/ClusterMetrics.vue
  frontend/src/components/ShootDetails/ShootMonitoringCard.vue
  frontend/src/store/index.js
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#940 update permission for service linked roles
  frontend/src/components/dialogs/SecretDialogAlicloudHelp.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#941 Bug/fix shoot table sorting
  frontend/src/store/index.js
  frontend/src/store/modules/shoots/getters.js
  frontend/src/store/modules/shoots/helper.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/views/ShootList.vue
  frontend/tests/unit/store.shoots.spec.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#891 Documents for working with the dashboard
  docs/Webterminals.md
  docs/connect-kubectl.md
  docs/images/00-create-project.png
  docs/images/01-access-1.png
  docs/images/01-open-terminal.png
  docs/images/01-provide-project-details.png
  docs/images/01-select-cluster.png
  docs/images/02-create-project-done.png
  docs/images/02-download.png
  docs/images/02-terminal.png
  docs/images/03-create-project-1.png
  docs/images/03-list-ns.png
  docs/images/04-delete-project.png
  docs/images/Add-service-account.png
  docs/images/Delete-service-account.png
  docs/images/Download-service-account-kubeconfig.png
  docs/images/Enter-service-account-details.png
  docs/images/Show-account-details.png
  docs/images/Show-details-of-OICD-login.png
  docs/project-ops.md
  docs/service-accounts.md
  docs/shoot.yaml
  docs/using-terminal.md
  docs/working-with-projects.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#948 Register dashboard doc component
  .docforge/manifest.yaml
Labels: needs/ok-to-test, size/xs

#950 Maintenance: removed local timezone conversions / do not use location…
  frontend/src/components/ShootDetails/ShootLifecycleCard.vue
  frontend/src/components/ShootHibernation/HibernationScheduleEvent.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootMaintenance/MaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/MaintenanceTime.vue
  frontend/src/mixins/shootItem.js
  frontend/src/store/index.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/TimeWithOffset.js
  frontend/src/utils/hibernationSchedule.js
  frontend/src/utils/index.js
  frontend/src/utils/validators.js
  frontend/src/views/NewShoot.vue
  frontend/tests/unit/utils.TimeWithOffset.spec.js
  frontend/tests/unit/utils.hibernationSchedule.spec.js
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#955 Handle html content correctly in access restrictions
  backend/lib/middleware.js
  frontend/src/components/ShootAccessRestrictions/AccessRestrictionChips.vue
  frontend/src/components/ShootAccessRestrictions/AccessRestrictions.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#957 Remove oidc configuration from necessary config (#727)
  backend/lib/config/gardener.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
