Repository gardener/dashboard, pull requests merged in 2021-09, with the labels that each got.

#1095 [master] Handle responses without body correctly
  .pnp.js
  .yarn/cache/cross-fetch-npm-3.1.4-45e4517cba-47b33bc773.zip
  .yarn/cache/jest-fetch-mock-npm-3.0.3-ac072ca8af-5c7dc1ba7a.zip
  .yarn/cache/promise-polyfill-npm-8.2.0-caaa5896b6-37a612596d.zip
  backend/lib/routes/members.js
  backend/test/acceptance/api.members.spec.js
  frontend/jest.setup.js
  frontend/package.json
  frontend/src/utils/api.js
  frontend/tests/unit/utils.api.spec.js
  yarn.lock
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1094 Fix HCloud Secret dialog
  frontend/src/components/dialogs/SecretDialogHCloud.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1089 add support for image references with digests in the helm charts
  charts/gardener-dashboard/templates/_helper.tpl
  charts/gardener-dashboard/templates/deployment.yaml
  charts/identity/templates/_helper.tpl
  charts/identity/templates/deployment.yaml
Labels: reviewed/lgtm, needs/ok-to-test

#1096 Update dexipd image tag to v2.30.0
  charts/identity/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1105 [hotfix-1.52] Fixed some issues
  .pnp.js
  .yarn/cache/caniuse-lite-npm-1.0.30001208-868ce46982-c8c9ffbd57.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001258-9014d665ba-ef97b5eb31.zip
  backend/lib/io.js
  backend/test/acceptance/io.spec.js
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
  frontend/src/views/ShootItemEditor.vue
  yarn.lock
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1102 [master] Fixed some issues
  .pnp.js
  .yarn/cache/caniuse-lite-npm-1.0.30001208-868ce46982-c8c9ffbd57.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001258-9014d665ba-ef97b5eb31.zip
  backend/lib/io.js
  backend/test/acceptance/io.spec.js
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
  frontend/src/views/ShootItemEditor.vue
  yarn.lock
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1106 [hotfix-1.52] fixed poppers could not be closed anymore
  frontend/src/components/GPopper.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1103 [master] fixed poppers could not be closed anymore
  frontend/src/components/GPopper.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1104 Use pull policy "IfNotPresent" for dashboard image by default
  charts/__tests__/gardener-dashboard/__snapshots__/deployment.spec.js.snap
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1107 Fix Error Code not properly rendered
  frontend/src/utils/errorCodes.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1108 fixed isShootLastOperationTypeControlPlaneMigrating logic
  frontend/src/mixins/shootItem.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1109 [hotfix-1.52] small fixes
  frontend/src/mixins/shootItem.js
  frontend/src/utils/errorCodes.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1110 [hotfix-1.52] Use pull policy "IfNotPresent" for dashboard image by default (#1104)
  charts/__tests__/gardener-dashboard/__snapshots__/deployment.spec.js.snap
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
