Repository gardener/dashboard, pull requests merged in 2021-03, with the labels that each got.

#959 Increase terminal timeout
  backend/lib/services/terminals/index.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#953 Theming via frontend configuration
  charts/__tests__/gardener-dashboard.spec.js
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
  docs/Theming.md
  frontend/public/index.html
  frontend/public/static/assets/favicon-16x16.png
  frontend/public/static/assets/favicon-32x32.png
  frontend/public/static/assets/favicon-96x96.png
  frontend/public/static/assets/favicon.ico
  frontend/public/static/assets/logo.svg
  frontend/src/assets/gardenlinux.svg
  frontend/src/components/MainNavigation.vue
  frontend/src/components/ShootDetails/ShootDetails.vue
  frontend/src/components/TerminalShortcut.vue
  frontend/src/components/TerminalShortcuts.vue
  frontend/src/components/VendorIcon.vue
  frontend/src/components/dialogs/InfoDialog.vue
  frontend/src/plugins/vuetify.theme.js
  frontend/src/store/index.js
  frontend/src/views/Account.vue
  frontend/src/views/Login.vue
  frontend/src/views/Members.vue
  frontend/src/views/Secrets.vue
  frontend/src/views/ShootList.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#962 Add error code for retryable configuration problems
  frontend/src/utils/errorCodes.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#963 Enh/no dialog warning colors
  frontend/src/components/DeleteCluster.vue
  frontend/src/components/ShootEditor.vue
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/dialogs/ActionButtonDialog.vue
  frontend/src/components/dialogs/ConfirmDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/MemberDialog.vue
  frontend/src/components/dialogs/MemberHelpDialog.vue
  frontend/src/components/dialogs/ProjectDialog.vue
  frontend/src/components/dialogs/SecretDialog.vue
  frontend/src/components/dialogs/SecretDialogDelete.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#965 Fix terminal drag n drop
  frontend/src/components/PositionalDropzone.vue
  frontend/src/lib/g-draggable.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#964 Place custom fields popper right
  frontend/src/components/ShootCustomField.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#966 Use raw value if html color code
  frontend/src/components/icons/IconBase.vue
  frontend/src/store/index.js
  frontend/src/utils/index.js
  frontend/tests/unit/utils.spec.js
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#968 Fixed some Dialog Colors
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/ProjectUserRow.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/InfoDialog.vue
  frontend/src/components/dialogs/SecretDialogDelete.vue
  frontend/src/views/Administration.vue
  frontend/src/views/Members.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#970 Removed unused color properties
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/dialogs/ActionButtonDialog.vue
  frontend/src/components/dialogs/ConfirmDialog.vue
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/TerminalSettingsDialog.vue
  frontend/src/components/dialogs/UnverifiedTerminalShortcutsDialog.vue
  frontend/src/components/dialogs/WebterminalServiceAccountDialog.vue
Labels: needs/ok-to-test, reviewed/lgtm

#973 Shoot Editor Improvements
  frontend/src/components/ShootEditor.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#979 Fixed autoscaler min / max value not showing up in worker description
  frontend/src/components/ShootWorkers/WorkerGroup.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#978 Detect Dark Mode Settings
  frontend/src/app.js
  frontend/src/components/CodeBlock.vue
  frontend/src/components/GSnotify.vue
  frontend/src/components/MainToolbar.vue
  frontend/src/components/ShootEditor.vue
  frontend/src/components/VendorIcon.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/store/index.js
  frontend/src/store/plugins/mediaPlugin.js
  frontend/src/views/ShootItemLoading.vue
  frontend/tests/unit/MainNavigation.spec.js
  frontend/tests/unit/NewShootDetails.spec.js
  frontend/tests/unit/StatusTag.spec.js
  frontend/tests/unit/WildcardSelect.spec.js
  frontend/tests/unit/matchMedia.mock
  frontend/tests/unit/store.index.spec.js
  frontend/tests/unit/store.shoots.spec.js
  frontend/tests/unit/utils.hibernationSchedule.spec.js
  frontend/tests/unit/utils.spec.js
Labels: needs/ok-to-test, reviewed/lgtm, size/m
