Repository gardener/dashboard, pull requests merged in 2021-08, with the labels that each got.

#1059 Enh/default cri
  frontend/src/components/NewShoot/NewShootDetails.vue
  frontend/src/components/ShootWorkers/ContainerRuntime.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
  frontend/src/store/index.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/index.js
  frontend/src/views/NewShoot.vue
  frontend/tests/unit/utils.spec.js
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#1072 Do not modify theme objects returned from store
  docs/deployment/theming.md
  frontend/src/store/index.js
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1073 Fix controllerregistrations permission issue
  backend/__fixtures__/controllerregistrations.js
  backend/lib/services/controllerregistrations.js
  backend/test/acceptance/__snapshots__/api.controllerregistrations.spec.js.snap
  backend/test/acceptance/api.controllerregistrations.spec.js
  frontend/src/components/dialogs/InfoDialog.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1074 [hotfix-1.51] Fix controllerregistrations permission issue
  backend/__fixtures__/controllerregistrations.js
  backend/lib/services/controllerregistrations.js
  backend/test/acceptance/__snapshots__/api.controllerregistrations.spec.js.snap
  backend/test/acceptance/api.controllerregistrations.spec.js
  frontend/src/components/dialogs/InfoDialog.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1075 [hotfix 1.51] Unify width of dialogs
  frontend/src/components/PurposeConfiguration.vue
  frontend/src/components/ShootAccessRestrictions/AccessRestrictionsConfiguration.vue
  frontend/src/components/ShootDns/DnsConfiguration.vue
  frontend/src/components/ShootHibernation/HibernationConfiguration.vue
  frontend/src/components/ShootMaintenance/MaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/MaintenanceStart.vue
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
  frontend/src/components/dialogs/TerminalSettingsDialog.vue
  frontend/src/components/dialogs/UnverifiedTerminalShortcutsDialog.vue
  frontend/src/components/dialogs/WebterminalServiceAccountDialog.vue
  frontend/src/views/Administration.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1076 [master] Unify width of dialogs
  frontend/src/components/PurposeConfiguration.vue
  frontend/src/components/ShootAccessRestrictions/AccessRestrictionsConfiguration.vue
  frontend/src/components/ShootDns/DnsConfiguration.vue
  frontend/src/components/ShootHibernation/HibernationConfiguration.vue
  frontend/src/components/ShootMaintenance/MaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/MaintenanceStart.vue
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
  frontend/src/components/dialogs/TerminalSettingsDialog.vue
  frontend/src/components/dialogs/UnverifiedTerminalShortcutsDialog.vue
  frontend/src/components/dialogs/WebterminalServiceAccountDialog.vue
  frontend/src/views/Administration.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1079 [master] Fix typo in TicketComment component
  frontend/src/components/ShootTickets/TicketComment.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1080 [hotfix-1.51] Fix typo in TicketComment component
  frontend/src/components/ShootTickets/TicketComment.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1081 Upgrade path-parse to version 1.0.7
  .pnp.js
  .yarn/cache/path-parse-npm-1.0.6-4a4c90546c-2eee4b93fb.zip
  .yarn/cache/path-parse-npm-1.0.7-09564527b7-6de0bfa37b.zip
  yarn.lock
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1084 [hotfix-1.51] Fixes regarding worker cri configuration
  frontend/src/components/ShootWorkers/ContainerRuntime.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
  frontend/src/store/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1082 [master] Fixes regarding worker cri configuration
  frontend/src/components/ShootWorkers/ContainerRuntime.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
  frontend/src/store/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1083 [master] DNS provider w/o secretBinding should be readonly
  frontend/src/components/SelectSecret.vue
  frontend/src/components/ShootDns/DnsProvider.vue
  frontend/src/components/ShootDns/DnsProviderRow.vue
  frontend/src/components/ShootDns/ManageDns.vue
  frontend/src/store/modules/shootStaging.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1087 [master] Do not show scrollbars when there is enough space.
  frontend/src/components/GPopper.vue
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/components/ShootHibernation/HibernationScheduleEvent.vue
  frontend/src/components/ShootMessageDetails.vue
  frontend/src/components/dialogs/SecretDialog.vue
  frontend/src/views/NewShoot.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1090 Fixed relative links
  README.md
Labels: reviewed/lgtm, needs/ok-to-test

#1091 [master] Fixed memory leak in cluster list
  frontend/src/app.js
  frontend/src/components/GPopper.vue
  frontend/src/plugins/bus.js
  frontend/src/utils/index.js
  frontend/src/views/Members.vue
  frontend/tests/unit/StatusTag.spec.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1092 [hotfix-1.51] Fixed memory leak in cluster list
  frontend/src/app.js
  frontend/src/components/GPopper.vue
  frontend/src/plugins/bus.js
  frontend/src/utils/index.js
  frontend/src/views/Members.vue
  frontend/tests/unit/StatusTag.spec.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test
