Repository gardener/dashboard, pull requests merged in 2021-06, with the labels that each got.

#1030 Update custom-field documentation
  docs/usage/custom-fields.md
Labels: lifecycle/stale, needs/ok-to-test, reviewed/lgtm, size/xs

#1023 Harmonize Cluster Warnings
  frontend/src/components/ConstraintWarning.vue
  frontend/src/components/SelfTerminationWarning.vue
  frontend/src/components/ShootDetails/ShootDetailsCard.vue
  frontend/src/components/ShootDetails/ShootLifecycleCard.vue
  frontend/src/components/ShootHibernation/HibernationScheduleWarning.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootMaintenance/MaintenanceStart.vue
  frontend/src/components/ShootMessages/ClusterExpirationMessage.vue
  frontend/src/components/ShootMessages/ConstraintMessage.vue
  frontend/src/components/ShootMessages/K8sExpirationMessage.vue
  frontend/src/components/ShootMessages/NoHibernationScheduleMessage.vue
  frontend/src/components/ShootMessages/ShootMessages.vue
  frontend/src/components/ShootMessages/WorkerGroupExpirationMessage.vue
  frontend/src/components/VersionExpirationWarning.vue
  frontend/src/utils/index.js
  frontend/tests/unit/utils.spec.js
Labels: lifecycle/rotten, needs/ok-to-test, reviewed/lgtm, size/xl

#1041 Self-contained shoot-item mixin
  frontend/src/components/ClusterMetrics.vue
  frontend/src/components/DeleteCluster.vue
  frontend/src/components/PurposeConfiguration.vue
  frontend/src/components/ReconcileStart.vue
  frontend/src/components/RetryOperation.vue
  frontend/src/components/RotateKubeconfigStart.vue
  frontend/src/components/ShootAccessRestrictions/AccessRestrictionsConfiguration.vue
  frontend/src/components/ShootAddons/AddonConfiguration.vue
  frontend/src/components/ShootDetails/GardenctlCommands.vue
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/components/ShootDetails/ShootDetails.vue
  frontend/src/components/ShootDetails/ShootDetailsCard.vue
  frontend/src/components/ShootDetails/ShootExternalToolsCard.vue
  frontend/src/components/ShootDetails/ShootInfrastructureCard.vue
  frontend/src/components/ShootDetails/ShootLifecycleCard.vue
  frontend/src/components/ShootDetails/ShootMonitoringCard.vue
  frontend/src/components/ShootDetails/TerminalShortcutsTile.vue
  frontend/src/components/ShootEditor.vue
  frontend/src/components/ShootHibernation/ChangeHibernation.vue
  frontend/src/components/ShootHibernation/HibernationConfiguration.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootMaintenance/MaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/MaintenanceStart.vue
  frontend/src/components/ShootMessages/ShootMessages.vue
  frontend/src/components/ShootSeedName.vue
  frontend/src/components/ShootStatus.vue
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/components/StatusTags.vue
  frontend/src/components/TerminalListTile.vue
  frontend/src/components/TerminalShortcut.vue
  frontend/src/components/TerminalTarget.vue
  frontend/src/components/TicketsCard.vue
  frontend/src/components/dialogs/ActionButtonDialog.vue
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
  frontend/src/mixins/shootItem.js
  frontend/src/views/ShootItem.vue
  frontend/src/views/ShootItemEditor.vue
  frontend/src/views/ShootItemTerminal.vue
  frontend/src/views/ShootList.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#1044 Allow modification of Container Runtime for existing workers
  frontend/src/components/ShootWorkers/ContainerRuntime.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1047 Proposes some minor changes
  frontend/src/store/modules/shoots/getters.js
  frontend/src/store/modules/shoots/helper.js
  frontend/src/views/ShootList.vue
  frontend/tests/unit/store.shoots.spec.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/m

#1048 Fixed `shoot-content` renaming
  frontend/src/views/NewShootEditor.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1040 No operator action required issues
  frontend/src/components/ShootMessageDetails.vue
  frontend/src/components/ShootStatus.vue
  frontend/src/router/guards.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/errorCodes.js
  frontend/src/views/ShootList.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1021 Improved search capabilities
  frontend/src/store/modules/shoots/getters.js
  frontend/src/store/modules/shoots/helper.js
  frontend/src/views/ShootList.vue
  frontend/tests/unit/store.shoots.spec.js
Labels: lifecycle/rotten, needs/ok-to-test, reviewed/lgtm, size/m

#1051 Fix privileged terminal container bug
  backend/lib/services/terminals/index.js
  frontend/src/components/GTerminal.vue
  frontend/src/components/TerminalSettings.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1052 Remove circular dependencies
  .pnp.js
  .yarn/cache/circular-dependency-plugin-npm-5.2.2-f7f25d48eb-1f60639470.zip
  frontend/package.json
  frontend/src/components/GSplitpane.vue
  frontend/src/components/GTerminal.vue
  frontend/src/components/NewShoot/NewShootDetails.vue
  frontend/src/components/ShootDetails/ShootLifecycleCard.vue
  frontend/src/components/ShootEditor.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootMessages/ShootMessages.vue
  frontend/src/components/ShootVersion/ShootVersion.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/lib/xterm-addon-focus.js
  frontend/src/mixins/shootItem.js
  frontend/src/store/index.js
  frontend/src/store/modules/draggable.js
  frontend/src/store/modules/infrastructureSecrets.js
  frontend/src/store/modules/members.js
  frontend/src/store/modules/projects.js
  frontend/src/store/modules/shoots/getters.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/store/modules/tickets.js
  frontend/src/utils/Emitter.js
  frontend/src/utils/hibernationSchedule.js
  frontend/src/utils/index.js
  frontend/tests/unit/utils.hibernationSchedule.spec.js
  frontend/tests/unit/utils.spec.js
  frontend/vue.config.js
  yarn.lock
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#1053 Fix text color on dark mode
  frontend/src/components/TerminalSettings.vue
Labels: needs/ok-to-test, needs/review, size/xs
