Repository gardener/dashboard, pull requests merged in 2021-04, with the labels that each got.

#987 Fixed typo
  frontend/src/mixins/shootItem.js
Labels: needs/ok-to-test, needs/review, size/xs

#986 Add copy button for shoot name and seed name
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootSeedName.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#980 Chart assets
  charts/gardener-dashboard/templates/configmap-assets.yaml
  charts/gardener-dashboard/templates/deployment.yaml
  charts/gardener-dashboard/values.yaml
  docs/Theming.md
Labels: reviewed/lgtm, size/s

#992 Replace moment-timezone with dayjs
  .pnp.js
  .yarn/cache/caniuse-lite-npm-1.0.30001208-868ce46982-c8c9ffbd57.zip
  .yarn/cache/dayjs-npm-1.10.4-e450424eab-3b7bb2232f.zip
  .yarn/cache/lodash.difference-npm-4.5.0-7a179a50e1-7a2c297cf5.zip
  .yarn/cache/moment-locales-webpack-plugin-npm-1.2.0-7c62d54698-a1613eaa41.zip
  .yarn/cache/moment-npm-2.29.0-f9cef938dc-ad48501913.zip
  .yarn/cache/moment-npm-2.29.1-787d9fdafd-86729013fe.zip
  .yarn/cache/moment-timezone-data-webpack-plugin-npm-1.3.0-a176742e2a-30466ae123.zip
  .yarn/cache/moment-timezone-npm-0.5.31-541ea51e9e-db8c241301.zip
  backend/lib/services/terminals/terminalBootstrap.js
  backend/package.json
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/components/ShootHibernation/HibernationScheduleEvent.vue
  frontend/src/components/ShootMaintenance/MaintenanceTime.vue
  frontend/src/components/TicketsCard.vue
  frontend/src/store/index.js
  frontend/src/utils/hibernationSchedule.js
  frontend/src/utils/index.js
  frontend/src/utils/moment.js
  frontend/src/views/Account.vue
  frontend/tests/unit/utils.hibernationSchedule.spec.js
  frontend/tests/unit/utils.moment.spec.js
  frontend/vue.config.js
  packages/kube-client/__tests__/cache.test.js
  packages/kube-client/lib/cache/Reflector.js
  packages/kube-client/package.json
  yarn.lock
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#1003 Fixed alternating row background in dark mode
  frontend/src/components/CodeBlock.vue
  frontend/src/components/GSnotify.vue
  frontend/src/components/MainToolbar.vue
  frontend/src/components/NewShoot/NewShootSelectInfrastructure.vue
  frontend/src/components/ShootAccessRestrictions/AccessRestrictions.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/VendorIcon.vue
  frontend/src/sass/main.scss
  frontend/src/views/ShootItemLoading.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#1002 Use the AWS IAM policy from g/provider-aws
  frontend/src/components/dialogs/SecretDialogAws.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1006 Fixed maintenance time window calculation
  frontend/src/utils/index.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
