Repository gardener/dashboard, pull requests merged in 2021-05, with the labels that each got.

#997 Show copy button only if mouse over parent element
  frontend/src/components/AutoHide.vue
  frontend/src/components/ShootListRow.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1009 Do not set .spec.provider.controlPlaneConfig.zone for alicloud
  frontend/src/utils/createShoot.js
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#1007 Apply the upcoming changes to the AWS IAM policy
  frontend/src/components/dialogs/SecretDialogAws.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#971 Documentation Refactoring & Improvements
  README.md
  docs/README.md
  docs/architecture/README.md
  docs/concepts/webterminals.md
  docs/deployment/access-restrictions.md
  docs/deployment/theming.md
  docs/development/local-setup.md
  docs/development/testing.md
  docs/images/access-restrictions-1.png
  docs/images/access-restrictions-2.png
  docs/images/architecture-1.png
  docs/images/architecture-2.png
  docs/images/architecture-3.png
  docs/images/architecture-4.png
  docs/images/custom-fields-1.png
  docs/images/custom-fields-2.png
  docs/images/custom-fields-3.png
  docs/images/custom-fields-4.png
  docs/images/dashboard-demo.gif
  docs/images/terminal-shortcuts-1.png
  docs/images/terminal-shortcuts-2.png
  docs/images/terminal-shortcuts-3.png
  docs/images/terminal-shortcuts-4.png
  docs/images/terminal-shortcuts-5.png
  docs/images/terminal-shortcuts-6.png
  docs/images/terminal-shortcuts-7.png
  docs/images/webterminals-1.png
  docs/usage/connect-kubectl.md
  docs/usage/custom-fields.md
  docs/usage/project-operations.md
  docs/usage/shoot.yaml
  docs/usage/terminal-shortcuts.md
  docs/usage/using-terminal.md
  docs/usage/working-with-projects.md
  docs/usage/working-with-service-accounts.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#790 Support Configuration of Container Runtimes
  frontend/src/components/ShootWorkers/ContainerRuntime.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
  frontend/src/store/index.js
Labels: kind/discussion, lifecycle/stale, needs/ok-to-test, needs/review, size/m

#1010 Fix lint issue
  frontend/src/components/dialogs/SecretDialogAws.vue
Labels: needs/ok-to-test, needs/review, size/xs

#1012 Do not auto fix frontend lint errors in docker build
  frontend/package.json
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1001 Helm chart enhancements
  .pnp.js
  .vscode/extensions.json
  .vscode/settings.json
  backend/__fixtures__/config.js
  backend/lib/config/gardener.js
  backend/test/config.spec.js
  charts/__fixtures__/gardener-dashboard.js
  charts/__fixtures__/helm.js
  charts/__fixtures__/helper.js
  charts/__fixtures__/identity.js
  charts/__fixtures__/index.js
  charts/__tests__/gardener-dashboard.spec.js
  charts/__tests__/gardener-dashboard/__snapshots__/configmap-assets.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/ingress.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/rbac.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/secrets.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/service.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/serviceaccount.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/vpa.spec.js.snap
  charts/__tests__/gardener-dashboard/configmap-assets.spec.js
  charts/__tests__/gardener-dashboard/configmap.spec.js
  charts/__tests__/gardener-dashboard/deployment.spec.js
  charts/__tests__/gardener-dashboard/ingress.spec.js
  charts/__tests__/gardener-dashboard/rbac.spec.js
  charts/__tests__/gardener-dashboard/secrets.spec.js
  charts/__tests__/gardener-dashboard/service.spec.js
  charts/__tests__/gardener-dashboard/serviceaccount.spec.js
  charts/__tests__/gardener-dashboard/vpa.spec.js
  charts/gardener-dashboard/templates/configmap-assets.yaml
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/templates/deployment.yaml
  charts/gardener-dashboard/templates/ingress.yaml
  charts/gardener-dashboard/templates/secret-github.yaml
  charts/gardener-dashboard/templates/secret-tls.yaml
  charts/gardener-dashboard/templates/vpa.yaml
  charts/gardener-dashboard/values.yaml
  charts/jest.setup.js
  charts/package.json
  charts/vpa.yaml
  frontend/jsconfig.json
  packages/test-utils/lib/helper.js
  vetur.config.js
  yarn.lock
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#1014 Fixed dependabot alerts
  .pnp.js
  .yarn/cache/hosted-git-info-npm-2.8.8-94a3928c03-3ecc389dc6.zip
  .yarn/cache/hosted-git-info-npm-2.8.9-62c44fa93f-cf4dfac9b9.zip
  backend/package.json
  charts/package.json
  frontend/package.json
  packages/kube-client/package.json
  packages/kube-config/package.json
  packages/request/package.json
  yarn.lock
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1015 Some changes to CRI Selection
  frontend/src/components/ShootWorkers/ContainerRuntime.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1018 Dashboard architecture overview documentation
  docs/architecture/README.md
  docs/images/architecture-1.png
  docs/images/architecture-2.png
  docs/images/architecture-3.png
  docs/images/architecture-4.png
  docs/images/webterminals-1.png
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1019 Upgrade socket.io
  .pnp.js
  .yarn/cache/@types-component-emitter-npm-1.2.10-95c27b794b-868a9a0069.zip
  .yarn/cache/@types-cookie-npm-0.4.0-2e6e63f5fe-be9ef4172b.zip
  .yarn/cache/@types-cors-npm-2.8.10-53b686e0da-c3f3d6feee.zip
  .yarn/cache/@types-node-npm-14.11.2-53170144b7-3badcce399.zip
  .yarn/cache/@types-node-npm-15.3.0-7ebc66d6bc-44039665ab.zip
  .yarn/cache/after-npm-0.8.2-7e7b7e3869-ac1e164f62.zip
  .yarn/cache/arraybuffer.slice-npm-0.0.7-c409adb178-d7775846f0.zip
  .yarn/cache/base64-arraybuffer-npm-0.1.4-2f8efc60e0-be8207c755.zip
  .yarn/cache/base64-arraybuffer-npm-0.1.5-64a2fbae81-9ae66a41b8.zip
  .yarn/cache/better-assert-npm-1.0.2-c9e69d4278-bc6a68fcd5.zip
  .yarn/cache/blob-npm-0.0.5-5e6b11bda5-41fbd9f746.zip
  .yarn/cache/callsite-npm-1.0.0-897924017b-5940b23533.zip
  .yarn/cache/component-bind-npm-1.0.0-c4b6dae2b7-afbea09480.zip
  .yarn/cache/component-emitter-npm-1.2.1-b9e2b2aee2-faa45682ad.zip
  .yarn/cache/component-inherit-npm-0.0.3-8f67384b1a-b0caec5757.zip
  .yarn/cache/cookie-npm-0.3.1-111f39dba6-5fb6caf84d.zip
  .yarn/cache/cookie-npm-0.4.1-cc5e2ebb42-b8e0928e3e.zip
  .yarn/cache/cors-npm-2.8.5-c9935a2d12-c83e88c154.zip
  .yarn/cache/debug-npm-4.1.1-540248b3aa-3601a6ce96.zip
  .yarn/cache/debug-npm-4.3.2-f0148b6afe-5543570879.zip
  .yarn/cache/engine.io-client-npm-3.4.3-cfef537d97-d64ef2bf67.zip
  .yarn/cache/engine.io-client-npm-5.1.1-35188532ad-4d918ab302.zip
  .yarn/cache/engine.io-npm-3.4.2-9183b38664-e581ca0414.zip
  .yarn/cache/engine.io-npm-5.1.1-c14adf15d7-ff39804a59.zip
  .yarn/cache/engine.io-parser-npm-2.2.0-8731f80937-cd467b8b12.zip
  .yarn/cache/engine.io-parser-npm-4.0.2-50c8845f23-fe5543911f.zip
  .yarn/cache/has-binary2-npm-1.0.3-a9954e86d3-1a80bcdcef.zip
  .yarn/cache/indexof-npm-0.0.1-b35b810950-23dd379c2d.zip
  .yarn/cache/isarray-npm-2.0.1-ef99c2575f-1387ed49e8.zip
  .yarn/cache/object-component-npm-0.0.3-7a1c300372-ae3417629f.zip
  .yarn/cache/parseqs-npm-0.0.5-2dddb68b0b-46444c9a5b.zip
  .yarn/cache/parseqs-npm-0.0.6-7d7191eb92-9e095b898b.zip
  .yarn/cache/parseuri-npm-0.0.5-04da93ca87-5a16cd5292.zip
  .yarn/cache/parseuri-npm-0.0.6-0c11d6eb7b-ff7ad178b0.zip
  .yarn/cache/socket.io-adapter-npm-1.1.2-e3bfeecac6-a5cbd66049.zip
  .yarn/cache/socket.io-adapter-npm-2.3.0-92cd5064f5-98ac60aa5f.zip
  .yarn/cache/socket.io-client-npm-2.3.0-8c17c7bd5f-e38863a3e2.zip
  .yarn/cache/socket.io-client-npm-4.1.2-33b9c3b5ba-932a1eb0fe.zip
  .yarn/cache/socket.io-npm-2.3.0-b02d9c8904-12368e2b05.zip
  .yarn/cache/socket.io-npm-4.1.2-76b1d73688-006342e1a5.zip
  .yarn/cache/socket.io-parser-npm-3.3.0-204cd6caf9-9765ec0d68.zip
  .yarn/cache/socket.io-parser-npm-3.4.1-01e4bd3a9c-3c52dfe4c0.zip
  .yarn/cache/socket.io-parser-npm-4.0.4-1dfc284556-ee2ffffa30.zip
  .yarn/cache/to-array-npm-0.1.4-81386702bb-c25a6d5e97.zip
  .yarn/cache/ws-npm-6.1.4-7bee7fd05f-74c2245736.zip
  .yarn/cache/ws-npm-7.3.1-0fa30fe373-9302f1f665.zip
  .yarn/cache/ws-npm-7.4.5-5c28d7e14e-20731aa107.zip
  .yarn/cache/xmlhttprequest-ssl-npm-1.5.5-7c88d54520-8bb71857be.zip
  backend/lib/security/index.js
  backend/package.json
  frontend/package.json
  frontend/src/utils/Emitter.js
  yarn.lock
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#1020 Fixed Ticket ADD COMMENT styling
  frontend/src/components/ShootTickets/Ticket.vue
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1008 Upgrade to node version 16
  .yarn/plugins/@yarnpkg/plugin-production-install.cjs
  .yarnrc.yml
  Dockerfile
  backend/package.json
  charts/package.json
  constraints.pro
  frontend/package.json
  package.json
  packages/kube-client/package.json
  packages/kube-config/package.json
  packages/logger/package.json
  packages/request/package.json
  packages/test-utils/package.json
Labels: lifecycle/rotten, needs/ok-to-test, reviewed/lgtm, size/s

#1022 Fix the custom-fields example
  docs/usage/custom-fields.md
Labels: needs/ok-to-test, needs/review, size/xs

#1025 [master] Fix http2 library response processing
  packages/request/lib/Client.js
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1027 Support http response content compression
  packages/request/__tests__/acceptance.test.js
  packages/request/__tests__/client.test.js
  packages/request/lib/Client.js
  packages/request/lib/SessionPool.js
  packages/request/package.json
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#1028 [master] Support http response content compression
  packages/request/__tests__/acceptance.test.js
  packages/request/__tests__/client.test.js
  packages/request/lib/Client.js
  packages/request/lib/SessionPool.js
  packages/request/package.json
Labels: needs/ok-to-test, reviewed/lgtm, size/m
