Repository gardener/dashboard, pull requests merged in 2022-07, with the labels that each got.

#1247 terminal: use TokenRequest to get service account token
  backend/lib/services/terminals/index.js
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
  backend/test/acceptance/api.terminals.spec.js
  charts/__tests__/gardener-dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/configmap.spec.js
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1239 Show user error as dedicated icon
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootStatus.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1250 fixed class
  frontend/src/components/ShootStatus.vue
Labels: needs/review, size/xs, needs/ok-to-test

#1254 Use scratch as base image
  Dockerfile
  backend/test/docker.spec.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1222 Drop usage of <shoot>.kubeconfig for Terminals
  backend/__fixtures__/helper.js
  backend/__fixtures__/shoots.js
  backend/lib/services/terminals/index.js
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
  backend/test/acceptance/api.terminals.spec.js
  packages/kube-client/__tests__/client.test.js
  packages/kube-client/lib/Client.js
  packages/kube-client/lib/resources/GardenerCore.js
  packages/kube-client/lib/resources/index.js
  packages/kube-client/lib/util.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1257 Disable experimental ESM loader
  .pnp.loader.mjs
  .yarnrc.yml
  Dockerfile
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1255 Update the Azure secret dialog
  frontend/src/components/dialogs/SecretDialogAzure.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1258 Table menu should be scrollable
  frontend/src/components/TableColumnSelection.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1260 Update mount path hint
  frontend/src/components/TerminalSettings.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1252 Show terminating and failed projects
  backend/__fixtures__/projects.js
  backend/lib/routes/namespaces.js
  backend/lib/services/projects.js
  backend/test/acceptance/__snapshots__/api.projects.spec.js.snap
  backend/test/services.projects.spec.js
  frontend/src/components/MainNavigation.vue
  frontend/src/components/NotReadyProjectWarning.vue
  frontend/src/components/StaleProjectWarning.vue
  frontend/src/store/modules/projects.js
  frontend/src/utils/index.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1266 Fix mountPath of assets
  charts/gardener-dashboard/templates/deployment.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1263 Hide oidc login if not configured
  backend/lib/config/gardener.js
  backend/test/acceptance/__snapshots__/config.spec.js.snap
  frontend/src/views/Login.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
