Repository gardener/dashboard, pull requests merged in 2022-06, with the labels that each got.

#1216 Add serviceaccountmanager role
  docs/usage/working-with-service-accounts.md
  frontend/src/components/dialogs/MemberDialog.vue
  frontend/src/components/dialogs/MemberHelpDialog.vue
  frontend/src/utils/index.js
  frontend/src/views/Members.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test, reviewed/do-not-merge

#1227 fix bump version of frontend and backend
  .ci/bump_version
  .yarn/versions/4060e1f6.yml
  frontend/package.json
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1228 Fixed some minor layout issues
  frontend/src/components/ShootDetails/ShootDetails.vue
  frontend/src/components/ShootDns/ManageDns.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/dialogs/MemberDialog.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1236 Fixed seed selector logic
  backend/__fixtures__/seeds.js
  backend/lib/services/cloudprofiles.js
  backend/test/acceptance/__snapshots__/api.cloudprofiles.spec.js.snap
  backend/test/acceptance/__snapshots__/api.seeds.spec.js.snap
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1237 Minor Fixes
  frontend/src/components/ShootDns/ManageDns.vue
  frontend/src/components/ShootStatus.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1230 Add support to define application credentials
  frontend/src/components/dialogs/SecretDialogOpenstack.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1241 TimeString / ExternalLink improvements
  frontend/src/components/ExternalLink.vue
  frontend/src/components/LinkListTile.vue
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/ShootDetails/ShootDetailsCard.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootMessages/ClusterExpirationMessage.vue
  frontend/src/components/ShootMessages/K8sExpirationMessage.vue
  frontend/src/components/ShootMessages/WorkerGroupExpirationMessage.vue
  frontend/src/components/ShootTickets/Ticket.vue
  frontend/src/components/ShootTickets/TicketComment.vue
  frontend/src/components/StaleProjectWarning.vue
  frontend/src/components/TimeString.vue
  frontend/src/views/Administration.vue
  frontend/src/views/Members.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1242 Upgrade node version and alpine docker image
  Dockerfile
  backend/package.json
  backend/test/docker.spec.js
  charts/package.json
  constraints.pro
  frontend/package.json
  package.json
  packages/kube-client/package.json
  packages/kube-config/package.json
  packages/logger/package.json
  packages/request/package.json
  packages/test-utils/package.json
Labels: reviewed/lgtm, size/s, needs/ok-to-test
