Repository gardener/dashboard, pull requests merged in 2022-08, with the labels that each got.

#1267 Split config into public and authenticated endpoint
  .gitignore
  backend/__fixtures__/config.js
  backend/lib/api.js
  backend/lib/app.js
  backend/lib/config/gardener.js
  backend/lib/routes/config.js
  backend/lib/routes/index.js
  backend/test/acceptance/__snapshots__/config.spec.js.snap
  backend/test/acceptance/config.spec.js
  charts/__tests__/gardener-dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/configmap.spec.js
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/templates/deployment.yaml
  frontend/public/login-config.json
  frontend/src/router/guards.js
  frontend/src/utils/api.js
  frontend/src/views/Login.vue
  frontend/vue.config.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1272 Bump dex version to v2.33.0-distroless
  charts/identity/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1270 Login screen: add skeleton loader
  frontend/src/views/Login.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1275 Document external tools in charts
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1274 Link to ticket (github issue) instead of shoot details
  frontend/src/components/ShootListRow.vue
  frontend/src/store/modules/tickets.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1262 Trigger control plane migration
  backend/__fixtures__/shoots.js
  backend/lib/routes/shoots.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  frontend/src/components/SeedConfiguration.vue
  frontend/src/components/ShootDetails/ShootInfrastructureCard.vue
  frontend/src/mixins/shootItem.js
  frontend/src/store/index.js
  frontend/src/utils/api.js
  packages/kube-client/__tests__/resources.test.js
  packages/kube-client/lib/mixins.js
Labels: size/l, needs/ok-to-test, needs/second-opinion

#1249 Implemented Disable Gardener provided static admin kubeconfig
  backend/lib/routes/shoots.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  frontend/src/components/NewShoot/NewShootDetails.vue
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/components/StaticTokenKubeconfigConfiguration.vue
  frontend/src/components/StaticTokenKubeconfigSwitch.vue
  frontend/src/mixins/shootItem.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/api.js
  frontend/src/views/NewShoot.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1280 Docforge version update in check-docforge.sh
  .ci/check-docforge
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
