Repository gardener/dashboard, pull requests merged in 2022-10, with the labels that each got.

#1303 Bump dex version to v2.35.1-distroless
  charts/identity/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1300 Show gardenctl target cluster for non-admins
  frontend/src/components/ShootDetails/GardenctlCommands.vue
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/store/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1302 Create orphaned service account on member update
  backend/lib/services/members/MemberManager.js
  backend/test/services.members.spec.js
  frontend/src/components/dialogs/MemberDialog.vue
  frontend/src/views/Members.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1307 Disable delete button for deleted service account
  backend/lib/services/members/Member.js
  backend/lib/services/members/SubjectList.js
  backend/test/services.members.spec.js
  frontend/src/components/ProjectServiceAccountRow.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1306 Remove redundant loadBalancerProvider in hcloud ControlPlaneConfig
  frontend/src/utils/createShoot.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1310 [hotfix-1.61] Remove redundant loadBalancerProvider in hcloud ControlPlaneConfig
  frontend/src/utils/createShoot.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1311 Support ManagedSeed on kube-client
  packages/kube-client/__tests__/client.test.js
  packages/kube-client/lib/groups.js
  packages/kube-client/lib/resources/GardenerSeedManagement.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1313 Alert label typo fix
  frontend/src/utils/errorCodes.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1317 Bump dex version to v2.35.3-distroless
  charts/identity/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1316 Update member help
  frontend/src/components/dialogs/MemberHelpDialog.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1321 Fixed: Machine images with additional properties not matched
  frontend/src/store/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1320 Adapted DNS Provider List getters to work with latest Gardener Releases
  backend/__fixtures__/controllerregistrations.js
  backend/test/acceptance/__snapshots__/api.controllerregistrations.spec.js.snap
  frontend/src/components/dialogs/SecretDialog.vue
  frontend/src/mixins/shootItem.js
  frontend/src/store/modules/gardenerExtensions.js
  frontend/src/store/modules/shootStaging.js
  frontend/src/views/Secrets.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1323 [hotfix-1.61] Bug/fix dns provider list hotfix
  backend/__fixtures__/controllerregistrations.js
  backend/test/acceptance/__snapshots__/api.controllerregistrations.spec.js.snap
  frontend/src/components/dialogs/SecretDialog.vue
  frontend/src/mixins/shootItem.js
  frontend/src/store/modules/gardenerExtensions.js
  frontend/src/store/modules/shootStaging.js
  frontend/src/views/Secrets.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1322 [hotfix-1.61] Fix: Machine images with additional properties not matched
  frontend/src/store/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1304 Show Floating IP Suffix / Prefix Name
  frontend/src/components/WildcardSelect.vue
  frontend/src/utils/wildcard.js
  frontend/tests/unit/WildcardSelect.spec.js
  frontend/tests/unit/utils.wildcard.spec.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1326 Forward request options correctly to the session pool
  backend/lib/hooks.js
  packages/request/__fixtures__/index.js
  packages/request/__tests__/agent.test.js
  packages/request/__tests__/session-id.test.js
  packages/request/lib/Agent.js
  packages/request/lib/Client.js
  packages/request/lib/SessionId.js
  packages/request/lib/SessionPool.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1295 Improved Openstack dialog
  backend/lib/services/cloudProviderSecrets.js
  backend/test/acceptance/__snapshots__/api.cloudProviderSecrets.spec.js.snap
  frontend/src/components/dialogs/SecretDialogOpenstack.vue
  frontend/src/utils/validators.js
  frontend/src/views/Secrets.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1312 Do not rely on secretRef for ManagedSeed
  backend/__fixtures__/index.js
  backend/__fixtures__/managedseeds.js
  backend/__fixtures__/secrets.js
  backend/lib/services/terminals/index.js
  backend/lib/services/terminals/terminalBootstrap.js
  backend/lib/services/terminals/utils.js
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
  backend/test/acceptance/api.terminals.spec.js
  backend/test/services.terminals.spec.js
  charts/__tests__/gardener-dashboard/application/__snapshots__/clusterrole.spec.js.snap
  charts/gardener-dashboard/charts/application/templates/clusterrole.yaml
  packages/kube-client/lib/Client.js
Labels: reviewed/lgtm, size/l, needs/ok-to-test

#1328 fix: theme (dark/light) not correctly applied on first visit
  frontend/jest.setup.js
  frontend/src/store/index.js
  frontend/src/store/plugins/mediaPlugin.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
