Repository gardener/dashboard, pull requests merged in 2022-04, with the labels that each got.

#1162 Improve local setup instructions
  docs/development/local-setup.md
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1173 Fixed ingress deployed by helm for k8s versions >=1.22
  charts/__tests__/gardener-dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/__snapshots__/ingress.spec.js.snap
  charts/_versions.tpl
  charts/gardener-dashboard/templates/ingress.yaml
  charts/identity/templates/ingress.yaml
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1178 Enh/support random monitoring credentials
  backend/__fixtures__/helper.js
  backend/__fixtures__/secrets.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1179 Allow configuration of node CLI options
  Dockerfile
  charts/__tests__/gardener-dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/deployment.spec.js
  charts/gardener-dashboard/templates/deployment.yaml
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1185 Migrate to use the networking.k8s.io/v1 API
  backend/lib/services/terminals/terminalBootstrap.js
  backend/test/services.terminals.spec.js
  packages/kube-client/lib/groups.js
  packages/kube-client/lib/resources/Networking.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1189 [hotfix-1.55]Fix identity ingress backend name
  charts/identity/templates/ingress.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1188 [master]Fix identity ingress backend name
  charts/identity/templates/ingress.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1169 Update manifest.yaml
  .ci/check-docforge
  .docforge/manifest.yaml
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1191 Support Azure Private DNS
  frontend/src/components/VendorIcon.vue
  frontend/src/components/dialogs/SecretDialogAzure.vue
  frontend/src/store/index.js
  frontend/src/views/Secrets.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
