Repository gardener/dashboard, pull requests merged in 2022-05, with the labels that each got.

#1192 Fix isShootStatusHibernated computed prop
  frontend/src/components/TerminalTarget.vue
  frontend/src/components/dialogs/CreateTerminalSessionDialog.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1195 Support service accounts with more than one secret
  backend/lib/services/members/MemberManager.js
  backend/test/services.members.spec.js
  frontend/src/components/messages/RotateServiceAccountSecret.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1182 Enh/improve custom cidr handling
  charts/__tests__/gardener-dashboard/__snapshots__/configmap.spec.js.snap
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/createShoot.js
  frontend/src/views/NewShoot.vue
  frontend/tests/unit/utils.createShoot.spec.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1190 Enh/readniness chips
  frontend/src/components/ShootListRow.vue
  frontend/src/components/StatusTag.vue
  frontend/src/components/StatusTags.vue
  frontend/src/views/ShootList.vue
  frontend/tests/unit/StatusTag.spec.js
  frontend/tests/unit/StatusTags.spec.js
Labels: size/l, needs/ok-to-test, needs/second-opinion

#1201 Update alpine, node and caniuse-lite
  .pnp.js
  .yarn/cache/caniuse-lite-npm-1.0.30001258-9014d665ba-ef97b5eb31.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001338-0f5d19b25f-89a9072725.zip
  Dockerfile
  backend/package.json
  charts/package.json
  constraints.pro
  frontend/package.json
  package.json
  packages/kube-client/package.json
  packages/kube-config/package.json
  packages/logger/package.json
  packages/request/package.json
  packages/test-utils/package.json
  yarn.lock
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1158 Remove shell
  charts/__tests__/gardener-dashboard/__snapshots__/configmap.spec.js.snap
  charts/gardener-dashboard/templates/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/src/components/GardenctlSettings.vue
  frontend/src/components/ShootDetails/GardenctlCommands.vue
  frontend/src/store/index.js
Labels: size/s, needs/ok-to-test, needs/rebase

#1203 Removed unnecessary import
  frontend/src/components/ShootDetails/ShootDetails.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1194 Add a warning in case new networks extend the network configuration
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/components/dialogs/ActionButtonDialog.vue
  frontend/src/components/dialogs/GDialog.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1198 Show available LB classes
  frontend/src/components/ShootDetails/LbClass.vue
  frontend/src/components/ShootDetails/ShootInfrastructureCard.vue
  frontend/src/components/WildcardSelect.vue
  frontend/src/store/index.js
  frontend/src/utils/wildcard.js
  frontend/tests/unit/store.index.spec.js
  frontend/tests/unit/utils.wildcard.spec.js
Labels: size/l, needs/ok-to-test, needs/second-opinion

#1205 Bug/fix net error, fix message padding
  frontend/src/components/ShootMessages/ShootMessages.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/store/index.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/createShoot.js
  frontend/src/views/NewShoot.vue
  frontend/tests/unit/utils.createShoot.spec.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1208 Handle empty cri case
  frontend/src/components/ShootWorkers/ContainerRuntime.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1209 Fix error when navigating away from shooteditor
  frontend/src/components/ShootEditor.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1210 Increase width of shoot worker dialog
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1211 Improve workspace settings
  .vscode/settings.json
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1213 Ignore GitGuardian cache file
  .gitignore
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1214 Update dexipd image tag to v2.31.1
  charts/identity/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1212 Improve workspace settings II
  .vscode/settings.json
  scripts/helper.cjs
  scripts/jest
  scripts/jest.cjs
  scripts/yarn.cjs
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1206 Add "deletion scheduled" to shoot status
  frontend/src/components/ShootStatus.vue
Labels: size/xs, needs/ok-to-test, needs/rebase

#1215 Enable compression and caching
  .pnp.js
  .yarn/cache/@gar-promisify-npm-1.1.3-ac1a325862-fb5cc69175.zip
  .yarn/cache/@npmcli-fs-npm-1.1.1-17f582e0b6-98da9b511b.zip
  .yarn/cache/@npmcli-move-file-npm-1.1.2-4f6c7b3354-d178d86a0a.zip
  .yarn/cache/@types-json-schema-npm-7.0.11-79462ae5ca-5f32333a4f.zip
  .yarn/cache/ajv-npm-6.12.6-4b5105e2b2-19a8f3b0a0.zip
  .yarn/cache/cacache-npm-15.3.0-a7e5239c6a-3ababe9fa2.zip
  .yarn/cache/compression-webpack-plugin-npm-6.1.1-3a2a65987e-cda226487a.zip
  .yarn/cache/destroy-npm-1.2.0-6a511802e2-fea2c89e4b.zip
  .yarn/cache/express-static-gzip-npm-2.1.7-b88261b8b1-35676e14b2.zip
  .yarn/cache/http-errors-npm-2.0.0-3f1c503428-505c185dd6.zip
  .yarn/cache/ms-npm-2.1.3-81ff3cfac1-6e721e648a.zip
  .yarn/cache/on-finished-npm-2.4.1-907af70f88-ed2f28508d.zip
  .yarn/cache/p-map-npm-4.0.0-4677ae07c7-d51e630d72.zip
  .yarn/cache/schema-utils-npm-3.1.1-8704647575-c4f4c4c511.zip
  .yarn/cache/semver-npm-7.3.7-3bfe704194-a9e88cefbc.zip
  .yarn/cache/send-npm-0.18.0-faadf6353f-a5de80329a.zip
  .yarn/cache/serialize-javascript-npm-5.0.1-8ffc173f09-97eef70a33.zip
  .yarn/cache/serve-static-npm-1.15.0-86c81879f5-5bf154f7dd.zip
  .yarn/cache/ssri-npm-8.0.1-a369e72ce2-d45f9a1d56.zip
  .yarn/cache/statuses-npm-2.0.1-81d2b97fee-d0d3024dd1.zip
  .yarn/cache/tar-npm-6.1.11-e6ac3cba9c-f6cd9b0d7c.zip
  .yarn/cache/toidentifier-npm-1.0.1-f759712599-2b5c573af9.zip
  backend/lib/app.js
  backend/lib/middleware.js
  backend/package.json
  frontend/package.json
  frontend/vue.config.js
  yarn.lock
Labels: reviewed/lgtm, size/xl, needs/ok-to-test
