Repository gardener/dashboard, pull requests merged in 2023-09, with the labels that each got.

#1539 [hotfix-1.69] Bug/hotfix error messages
  frontend/src/components/ShootHibernation/HibernationConfiguration.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
  frontend/src/store/index.js
  frontend/src/views/NewShootEditor.vue
  frontend/src/views/ShootItemEditor.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1541 Garden Terminal: make rolebinding configurable
  backend/lib/services/terminals/index.js
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1537 Add github app-auth chart test for `secret-github.yaml` template
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/secrets.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/secrets.spec.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1544 Fix vendor icon size
  frontend/src/components/GVendorIcon.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1540 [master] Show root cause for failed requests in appstore alerts
  frontend/src/store/app.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1545 Default costObject to empty string like purpose and description
  frontend/src/utils/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1546 Implementation of Lazy Loading for Copy to Clipboard Functionality
  frontend/src/components/GCopyBtn.vue
  frontend/src/components/GShootEditor.vue
  frontend/src/views/GAccount.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1548 Pin docker node image minor version
  .ci/pipeline_definitions
  Dockerfile
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1554 Make cluster access dialog persistent
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1555 Update semver in package.json
  .pnp.cjs
  .yarn/cache/lru-cache-npm-10.0.0-256d74bb20-18f101675f.zip
  backend/package.json
  frontend/package.json
  yarn.lock
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1556 Imporve focus mode tooltip formatting and tooltip background
  frontend/src/sass/settings.scss
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1558 Refresh rules
  frontend/src/components/Members/GMemberDialog.vue
  frontend/src/store/authz.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1562 Log error when when OIDC issuer discovery fails
  backend/lib/security/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1565 Remove terminal-bootstrap from pipeline
  .ci/pipeline_definitions
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1566 Fixes loading in placeholder components
  frontend/src/views/GProjectPlaceholder.vue
  frontend/src/views/GShootItemPlaceholder.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1569 Fixed bugs on create terminal dialog
  frontend/src/components/GTerminalTarget.vue
  frontend/src/components/dialogs/GCreateTerminalSessionDialog.vue
  frontend/src/composables/useTerminalConfig.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#1570 Fetch subject rules when the user is not assigned to any project yet
  frontend/src/composables/useApi/api.js
  frontend/src/store/authz.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1557 Enable focus mode and issue since column for non operator users
  frontend/src/store/localStorage.js
  frontend/src/views/GSettings.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test, area/ipcei

#1559 Fixed DNS popover alignment and link color
  frontend/src/components/ShootDns/GDnsProvider.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1571 Map pinia functions with mapActions
  frontend/src/components/GSeedConfiguration.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionsConfiguration.vue
  frontend/src/components/ShootDns/GDnsConfiguration.vue
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1531 Support Workerless Clusters
  frontend/__tests__/components/GNewShootDetails.spec.js
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GStaticTokenKubeconfigSwitch.vue
  frontend/src/components/GTerminal.vue
  frontend/src/components/GTerminalSettings.vue
  frontend/src/components/GTerminalSplitpanes.vue
  frontend/src/components/NewShoot/GNewShootDetails.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/components/ShootAddons/GManageAddons.vue
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/components/ShootDetails/GShootDetailsCard.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/components/ShootHibernation/GShootActionChangeHibernation.vue
  frontend/src/components/ShootMaintenance/GMaintenanceComponents.vue
  frontend/src/components/ShootMaintenance/GMaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/GShootActionMaintenanceStart.vue
  frontend/src/components/ShootWorkers/GManageWorkers.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
  frontend/src/components/ShootWorkers/GWorkerGroups.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/components/dialogs/GCreateTerminalSessionDialog.vue
  frontend/src/components/dialogs/GTerminalSettingsDialog.vue
  frontend/src/mixins/shootItem.js
  frontend/src/store/shoot/helper.js
  frontend/src/store/shootStaging.js
  frontend/src/views/GNewShoot.vue
  frontend/src/views/GShootItemEditor.vue
  frontend/src/views/GShootItemPlaceholder.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test, area/ipcei

#1575 Fixed some shoot item navigation issues
  frontend/src/components/GMainContent.vue
  frontend/src/components/GNotify.vue
  frontend/src/components/GSplitpane.vue
  frontend/src/router/routes.js
  frontend/src/store/app.js
  frontend/src/store/authn/index.js
  frontend/src/store/authz.js
  frontend/src/store/cloudProfile/index.js
  frontend/src/store/config.js
  frontend/src/store/gardenerExtension.js
  frontend/src/store/kubeconfig.js
  frontend/src/store/localStorage.js
  frontend/src/store/login.js
  frontend/src/store/member.js
  frontend/src/store/project.js
  frontend/src/store/quota/index.js
  frontend/src/store/secret.js
  frontend/src/store/seed.js
  frontend/src/store/shoot/index.js
  frontend/src/store/shootStaging.js
  frontend/src/store/socket/index.js
  frontend/src/store/terminal.js
  frontend/src/store/ticket.js
  frontend/src/views/GProjectPlaceholder.vue
  frontend/src/views/GShootItem.vue
  frontend/src/views/GShootItemPlaceholder.vue
  frontend/vite.config.js
Labels: reviewed/lgtm, size/l, reviewed/ok-to-test, needs/ok-to-test

#1576 use v-theme* class
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GVendorIcon.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1577 Remove unnecessary component name
  frontend/src/components/GDragNDroppableComponent.vue
  frontend/src/components/GSeedConfiguration.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionsConfiguration.vue
  frontend/src/components/ShootDetails/GCustomFieldsCard.vue
  frontend/src/components/dialogs/GUnverifiedTerminalShortcutsDialog.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1582 Increase hibernation configuration dialog width
  frontend/src/components/ShootHibernation/GHibernationConfiguration.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1579 Use text-medium-emphasis
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictions.vue
  frontend/src/components/ShootAddons/GManageAddons.vue
  frontend/src/views/GSettings.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1589 Fix issue when sla is not defined in frontend config
  frontend/src/store/config.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1588 Trim user input
  frontend/src/components/dialogs/GDialog.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1591 Support default node CIDR from cloud profile
  frontend/__tests__/stores/cloudProfile.spec.js
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/store/cloudProfile/index.js
  frontend/src/store/config.js
  frontend/src/store/shoot/helper.js
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test, area/ipcei
