Repository gardener/dashboard, pull requests merged in 2023-05, with the labels that each got.

#1479 Vue3 add member page
  .pnp.cjs
  .yarn/cache/downloadjs-npm-1.4.7-952a4ef987-4c546a28e7.zip
  frontend/package.json
  frontend/src/components/GAccountAvatar.vue
  frontend/src/components/GCopyBtn.vue
  frontend/src/components/GTableColumnSelection.vue
  frontend/src/components/Members/GAccountRoles.vue
  frontend/src/components/Members/GServiceAccountRow.vue
  frontend/src/components/Members/GUserRow.vue
  frontend/src/plugins/vuetify.js
  frontend/src/views/GMembers.vue
  yarn.lock
Labels: reviewed/ok-to-test, needs/review, size/xl, needs/second-opinion

#1489 Removed People paragraph from readme
  README.md
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1492 Fixed broken links - 2023.05
  docs/usage/project-operations.md
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1494 Replace references to Grafana and Loki with Plutono and Vali
  backend/lib/services/shoots.js
  frontend/src/components/ClusterMetrics.vue
  frontend/src/store/modules/shoots/helper.js
  frontend/src/store/modules/shoots/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1490 Adapt `NetworkPolicy`s
  charts/__tests__/gardener-dashboard/runtime/bootstrapper/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/gardener-dashboard/charts/runtime/templates/bootstrapper/deployment.yaml
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
Labels: kind/enhancement, reviewed/lgtm, area/networking, area/security, size/xs, needs/ok-to-test

#1493 Set dashboard ingress.spec.ingressClassName to nginx
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/ingress.spec.js.snap
  charts/gardener-dashboard/charts/runtime/templates/dashboard/ingress.yaml
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
