Repository gardener/dashboard, pull requests merged in 2023-01, with the labels that each got.

#1380 Stop setting the `.spec.provider.providerConfig.zone` field for OpenStack Shoots
  frontend/src/utils/createShoot.js
Labels: reviewed/lgtm, kind/cleanup, size/xs, needs/ok-to-test

#1384 Chart: Increase default resource limits and requests
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1235 Focus Cluster List
  frontend/src/components/GPopper.vue
  frontend/src/components/ShootListRow.vue
  frontend/src/components/ShootStatus.vue
  frontend/src/components/StatusTag.vue
  frontend/src/components/StatusTags.vue
  frontend/src/components/TableColumnSelection.vue
  frontend/src/mixins/shootItem.js
  frontend/src/store/modules/shoots/getters.js
  frontend/src/store/modules/shoots/helper.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/index.js
  frontend/src/views/ShootList.vue
  frontend/tests/unit/store.shoots.spec.js
  frontend/tests/unit/utils.spec.js
Labels: reviewed/lgtm, size/l, size/xl, needs/ok-to-test

#1389 fix: change contribution link to Contributor Guide on gardener.cloud
  CONTRIBUTING.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1392 fix: navigation home item color for light theme
  frontend/src/components/MainNavigation.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1393 Status Button Cleanup
  frontend/src/components/RetryOperation.vue
  frontend/src/components/ShootStatus.vue
Labels: needs/ok-to-test

#1377 Support gardenlogin kubeconfig
  backend/__fixtures__/configmaps.js
  backend/__fixtures__/index.js
  backend/__fixtures__/shoots.js
  backend/__mocks__/@gardener-dashboard/kube-config.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  frontend/src/components/CodeBlock.vue
  frontend/src/components/GardenctlConfigExample.vue
  frontend/src/components/GardenctlInfo.vue
  frontend/src/components/GardenloginInfo.vue
  frontend/src/components/ShootDetails/GardenctlCommands.vue
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/components/ShootDetails/ShootKubeconfig.vue
  frontend/src/components/StaticTokenKubeconfigConfiguration.vue
  frontend/src/views/ShootList.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#1396 Add reuse github action and fix lint errors
  .ci/check-docforge
  .github/workflows/reuse-tool-lint.yaml
  .reuse/dep5
  .vscode/settings.json
  backend/__fixtures__/serviceaccounts.js
  charts/vpa.yaml
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1387 Fixed chips for User and SA roles are wrapped even if there is enough space
  frontend/src/components/ProjectServiceAccountRow.vue
  frontend/src/components/ProjectUserRow.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1399 Fixes an occasionally failing test
  backend/test/acceptance/auth.spec.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1388 Maintenance Information Improvements
  frontend/src/components/ShootDetails/ShootLifecycleCard.vue
  frontend/src/components/ShootMessages/MaintenanceStatusMessage.vue
  frontend/src/components/ShootMessages/ShootMessages.vue
  frontend/src/mixins/shootItem.js
  frontend/src/utils/TimeWithOffset.js
  frontend/tests/unit/utils.TimeWithOffset.spec.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1401 Remove unused topic function
  frontend/src/store/modules/shoots/getters.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1405 Small typo fix for names that are too long
  frontend/src/components/NewShoot/NewShootDetails.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1402 Docs: Use gardenlogin kubeconfig
  docs/images/01-access-1.png
  docs/images/01-select-cluster.png
  docs/images/02-download.png
  docs/images/03-gardenlogin-info.png
  docs/usage/connect-kubectl.md
  frontend/src/components/ShootDetails/ShootAccessCard.vue
  frontend/src/components/ShootDetails/ShootKubeconfig.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1403 Docs: describe images for custom fields, highlight relevant sections
  docs/images/custom-fields-1.png
  docs/images/custom-fields-2.png
  docs/images/custom-fields-3.png
  docs/images/custom-fields-4.png
  docs/usage/custom-fields.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1406 Update local setup documentation
  docs/development/local-setup.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
