Repository gardener/dashboard, pull requests merged in 2023-02, with the labels that each got.

#1407 consider error codes from constraints
  frontend/src/store/modules/shoots/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1419 Added support for `gke-gcloud-auth-plugin`
  packages/kube-config/__tests__/kube-config.test.js
  packages/kube-config/lib/Config.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1420 [hotfix-1.66] Added support for `gke-gcloud-auth-plugin`
  packages/kube-config/__tests__/kube-config.test.js
  packages/kube-config/lib/Config.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1421 Add kubelogin plugin for connecting kubectl.
  docs/usage/connect-kubectl.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1424 Adjust the shoot ingress domain calculation
  backend/lib/services/shoots.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1408 Shoot owners and Gardener operators see the same monitoring links
  backend/__fixtures__/secrets.js
  backend/lib/routes/shoots.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  frontend/src/components/ClusterMetrics.vue
  frontend/src/store/index.js
  frontend/src/store/modules/shoots/index.js
  frontend/src/utils/api.js
  frontend/src/views/ShootItemTerminal.vue
Labels: size/l, needs/ok-to-test, needs/second-opinion

#1428 If provided, use config.clusterIdentity to build the gardenlogin kubeconfig
  backend/lib/services/shoots.js
  backend/test/services.shoots.spec.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1416 Fixed a couple of issues with focus mode
  frontend/src/components/ShootListRow.vue
  frontend/src/store/modules/shoots/index.js
  frontend/src/views/ShootList.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1422 Added access restrictions to issue template
  charts/gardener-dashboard/values.yaml
  frontend/src/components/ShootAccessRestrictions/AccessRestrictionChips.vue
  frontend/src/components/ShootDetails/ShootDetailsCard.vue
  frontend/src/components/TicketsCard.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
