Repository gardener/dashboard, pull requests merged in 2023-10, with the labels that each got.

#1590 Credential Rotation Fixes
  frontend/__tests__/components/GShootCredentialRotation.spec.js
  frontend/src/components/GCredentialTile.vue
  frontend/src/components/GListItemContent.vue
  frontend/src/components/GShootActionButton.vue
  frontend/src/components/GShootActionRotateCredentials.vue
  frontend/src/components/ShootDetails/GShootCredentialRotationCard.vue
  frontend/src/components/ShootDetails/GShootKubeconfig.vue
  frontend/src/components/ShootDetails/GShootLifecycleCard.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1587 Maintenance Dialog Improvements and Fixes
  .yarn/cache/@esbuild-darwin-x64-npm-0.18.20-767fe27d1b-8.zip
  frontend/__tests__/utils/index.spec.js
  frontend/src/components/ShootMaintenance/GMaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/GMaintenanceTime.vue
  frontend/src/components/ShootMaintenance/GShootActionMaintenanceStart.vue
  frontend/src/utils/index.js
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1599 Fixed some issues with workerless cluster creation
  frontend/src/components/NewShoot/GNewShootDetails.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/store/shoot/index.js
  frontend/src/store/shootStaging.js
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1601 Fixed broken links - 2023.10
  docs/README.md
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1598 Add support for projected volume kubeconfig
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/deployment.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
  charts/gardener-dashboard/values.yaml
Labels: kind/enhancement, reviewed/lgtm, size/m, area/security, needs/ok-to-test

#1600 Support OpenAPI v3
  backend/lib/openapi/index.js
  backend/lib/services/authorization.js
  backend/test/acceptance/openapi.spec.js
  frontend/__tests__/utils/shootEditorCompletions.spec.js
  frontend/src/components/GShootEditor.vue
  frontend/src/utils/shootEditorCompletions.js
  packages/kube-client/__tests__/non-resource-endpoints.test.js
  packages/kube-client/lib/nonResourceEndpoints/OpenAPI.js
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test, area/ipcei

#1602 OpenAPI logging - removed wrong assignment
  frontend/src/utils/shootEditorCompletions.js
Labels: needs/review, size/xs, needs/ok-to-test

#1604 Further customization improvements
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  docs/images/customization-dark-1.png
  docs/images/customization-dark-2.png
  docs/images/customization-dark-3.png
  docs/operations/customization.md
  frontend/src/App.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1608 Handle session expiration gracefully and fix autoLogin redirection
  backend/lib/auth.js
  backend/lib/security/index.js
  frontend/__tests__/utils/index.spec.js
  frontend/__tests__/utils/moment.spec.js
  frontend/src/components/GTimeString.vue
  frontend/src/router/guards.js
  frontend/src/store/authn/helper.js
  frontend/src/store/authn/index.js
  frontend/src/store/socket/helper.js
  frontend/src/utils/errors.js
  frontend/src/utils/index.js
  frontend/src/utils/moment.js
  frontend/src/views/GAccount.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1609 [hotfix-1.70] Removed wrong assignment (#1602)
  frontend/src/utils/shootEditorCompletions.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1610 [hotfix-1.70] Update GShootActionRotateCredentials.vue (#1603)
  frontend/src/components/GShootActionRotateCredentials.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1611 [hotfix-1.70] Further customization improvements (#1604)
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  docs/images/customization-dark-1.png
  docs/images/customization-dark-2.png
  docs/images/customization-dark-3.png
  docs/operations/customization.md
  frontend/src/App.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1612 [hotfix-1.70] Handle session expiration gracefully and fix autoLogin redirection (#1608)
  backend/lib/auth.js
  backend/lib/security/index.js
  frontend/__tests__/utils/index.spec.js
  frontend/__tests__/utils/moment.spec.js
  frontend/src/components/GTimeString.vue
  frontend/src/router/guards.js
  frontend/src/store/authn/helper.js
  frontend/src/store/authn/index.js
  frontend/src/store/socket/helper.js
  frontend/src/utils/errors.js
  frontend/src/utils/index.js
  frontend/src/utils/moment.js
  frontend/src/views/GAccount.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1614 [hotfix-1.70] Remove duplicative tooltip
  frontend/src/components/GShootListRow.vue
  frontend/src/views/GAdministration.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1613 [hotfix 1.70] fixes memory leaks in `GTimeString` and `localStorage` store
  frontend/src/components/GTimeString.vue
  frontend/src/store/localStorage.js
Labels: reviewed/lgtm, size/l, reviewed/ok-to-test, needs/ok-to-test

#1622 Configure CVSS Rescoring
  .ci/pipeline_definitions
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1627 Add assets checksum annotation on deployment
  charts/__tests__/gardener-dashboard/runtime/dashboard/deployment.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1629 Fix: scroll alert into view
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1624 Keep the current URL path if the user is automatically logged out
  frontend/__tests__/stores/authn.spec.js
  frontend/__tests__/stores/socket.spec.js
  frontend/src/components/GMainToolbar.vue
  frontend/src/router/guards.js
  frontend/src/store/authn/helper.js
  frontend/src/store/authn/index.js
  frontend/src/store/socket/helper.js
  frontend/src/store/socket/index.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1632 Fixed project owner selection via mouse click
  frontend/src/components/editable/GEditableAccount.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1625 Fixed vsphere load balancer classes selection
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
