Repository gardener/dashboard, pull requests merged in 2023-03, with the labels that each got.

#1414 Show machine types / volume types independent of zone selection
  frontend/src/components/NewShoot/NewShootInfrastructureDetails.vue
  frontend/src/components/ShootWorkers/MachineType.vue
  frontend/src/components/ShootWorkers/VolumeType.vue
  frontend/src/components/ShootWorkers/WorkerInputGeneric.vue
  frontend/src/store/index.js
  frontend/src/store/modules/shoots/index.js
  frontend/tests/unit/store.index.spec.js
Labels: size/l, needs/ok-to-test, needs/second-opinion

#1426 Bug/fix animation issues
  frontend/src/components/ControlPlaneHighAvailability/ManageControlPlaneHighAvailability.vue
  frontend/src/components/GAlert.vue
  frontend/src/components/GMessage.vue
  frontend/src/components/ShootDetails/TerminalShortcutsTile.vue
  frontend/src/components/ShootDns/DnsProviderRow.vue
  frontend/src/components/ShootDns/ManageDns.vue
  frontend/src/components/ShootEditor.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#1430 Added optional region field to aws dns secret dialog
  backend/lib/services/cloudProviderSecrets.js
  frontend/src/components/dialogs/SecretDialogAws.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1432 Added secret details to infrastructure card
  frontend/src/components/PurposeConfiguration.vue
  frontend/src/components/SecretDetailsItemContent.vue
  frontend/src/components/SecretRowDns.vue
  frontend/src/components/SecretRowInfra.vue
  frontend/src/components/ShootDetails/ShootInfrastructureCard.vue
  frontend/src/components/ShootDns/DnsProvider.vue
  frontend/src/views/Secrets.vue
Labels: size/l, needs/ok-to-test, needs/second-opinion

#1438 Support alpine architecture `x86_64` and `aarch64`
  .ci/pipeline_definitions
  Dockerfile
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1439 Adapt `NetworkPolicys` according to recent refactorings
  backend/lib/services/terminals/index.js
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
Labels: kind/enhancement, area/dev-productivity, reviewed/lgtm, reviewed/ok-to-test, area/networking, area/security, area/ops-productivity, size/xs, needs/ok-to-test, platform/gcp

#1411 add prometheus metrics endpoint
  .dockerignore
  .pnp.cjs
  .yarn/cache/bintrees-npm-1.0.2-b28feeda03-56a52b7d36.zip
  .yarn/cache/prom-client-npm-14.1.1-922a88d5b4-7ff3e85636.zip
  .yarn/cache/response-time-npm-2.3.2-e5c67ab5c5-2520478f03.zip
  .yarn/cache/tdigest-npm-0.1.2-b73cfcf726-44de824675.zip
  backend/__mocks__/@gardener-dashboard/monitor.js
  backend/lib/app.js
  backend/lib/config/gardener.js
  backend/lib/hooks.js
  backend/lib/middleware.js
  backend/lib/routes/cloudProviderSecrets.js
  backend/lib/routes/cloudprofiles.js
  backend/lib/routes/config.js
  backend/lib/routes/gardenerExtensions.js
  backend/lib/routes/info.js
  backend/lib/routes/members.js
  backend/lib/routes/namespaces.js
  backend/lib/routes/resourceQuotas.js
  backend/lib/routes/seeds.js
  backend/lib/routes/shoots.js
  backend/lib/routes/terminals.js
  backend/lib/routes/tickets.js
  backend/lib/routes/user.js
  backend/lib/server.js
  backend/package.json
  backend/server.js
  backend/test/config.spec.js
  backend/test/server.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
  charts/gardener-dashboard/values.yaml
  packages/monitor/__mocks__/@gardener-dashboard/logger.js
  packages/monitor/__mocks__/prom-client.js
  packages/monitor/__mocks__/response-time.js
  packages/monitor/__tests__/__snapshots__/metrics.test.js.snap
  packages/monitor/__tests__/acceptance/api.metrics.test.js
  packages/monitor/__tests__/app.test.js
  packages/monitor/__tests__/metrics.test.js
  packages/monitor/__tests__/monitors.test.js
  packages/monitor/jest.setup.js
  packages/monitor/lib/app.js
  packages/monitor/lib/index.js
  packages/monitor/lib/logger.js
  packages/monitor/lib/metrics.js
  packages/monitor/lib/monitors.js
  packages/monitor/package.json
  yarn.lock
Labels: reviewed/lgtm, size/xl, needs/ok-to-test

#1441 Add support for `onmetal` as infrastructure provider
  frontend/src/assets/onmetal.svg
  frontend/src/components/VendorIcon.vue
  frontend/src/store/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1443 Bump dexidp version to v2.36.0
  charts/identity/values.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1446 Added missing chart value for condition configuration to helm chart
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/deployment.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1449 Remove limits in default values
  charts/__tests__/gardener-dashboard/runtime/bootstrapper/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/gardener-dashboard/values.yaml
  charts/identity/values.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1400 enh: listen on lease obj to trigger ticket polling + restructure GH w…
  .pnp.cjs
  .vscode/settings.json
  .yarn/cache/p-limit-npm-3.1.0-05d2ede37f-7c3690c4db.zip
  .yarn/cache/yocto-queue-npm-0.1.0-c6c9a7db29-f77b3d8d00.zip
  backend/__fixtures__/env.js
  backend/__fixtures__/github.js
  backend/__fixtures__/index.js
  backend/__fixtures__/leases.js
  backend/__mocks__/p-limit.js
  backend/jest.setup.js
  backend/lib/app.js
  backend/lib/github/SyncManager.js
  backend/lib/github/index.js
  backend/lib/github/webhook.js
  backend/lib/github/webhook/handler.js
  backend/lib/github/webhook/index.js
  backend/lib/github/webhook/router.js
  backend/lib/github/webhook/verify.js
  backend/lib/hooks.js
  backend/lib/utils/index.js
  backend/lib/watches/index.js
  backend/lib/watches/leases.js
  backend/lib/watches/tickets.js
  backend/package.json
  backend/test/acceptance/webhook.spec.js
  backend/test/github.spec.js
  backend/test/hooks.spec.js
  backend/test/watches.spec.js
  charts/__tests__/gardener-dashboard/application/dashboard/__snapshots__/lease-github-webhook.spec.js.snap
  charts/__tests__/gardener-dashboard/application/dashboard/lease-github-webhook.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/deployment.spec.js
  charts/gardener-dashboard/charts/application/templates/dashboard/lease-github-webhook.yaml
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
  charts/gardener-dashboard/values.yaml
  packages/kube-client/lib/groups.js
  packages/kube-client/lib/resources/Coordination.js
  yarn.lock
Labels: reviewed/ok-to-test, size/xl, needs/ok-to-test, needs/rebase, needs/second-opinion

#1451 Run the helm chart unit tests as part of the pipeline check step.
  .ci/check
  .ci/pipeline_definitions
  .gitignore
  .vscode/settings.json
  Dockerfile
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1447 Fix/create shoot issues
  frontend/src/components/NewShoot/NewShootDetails.vue
  frontend/src/components/NewShoot/NewShootInfrastructureDetails.vue
  frontend/src/components/Purpose.vue
  frontend/src/components/ShootDns/ManageDns.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1454 fix: deleting just created comment was not propagated to UI
  backend/lib/github/webhook/handler.js
  backend/lib/github/webhook/router.js
  backend/lib/utils/index.js
  backend/test/acceptance/webhook.spec.js
  backend/test/github.spec.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1455 Enh/GitHub webhook logging
  backend/lib/github/SyncManager.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1457 force re-rendering of dialogs before re-using them
  frontend/src/components/ControlPlaneHighAvailability/ControlPlaneHighAvailabilityConfiguration.vue
  frontend/src/components/ControlPlaneHighAvailability/ManageControlPlaneHighAvailability.vue
  frontend/src/components/ShootDns/ManageDns.vue
  frontend/src/components/ShootHibernation/HibernationConfiguration.vue
  frontend/src/components/ShootHibernation/ManageHibernationSchedule.vue
  frontend/src/components/ShootWorkers/ManageWorkers.vue
  frontend/src/components/ShootWorkers/WorkerConfiguration.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1460 Rename prometheus metric for monitoring HTTP request durations in seconds
  backend/lib/api.js
  backend/lib/app.js
  backend/lib/github/webhook/router.js
  packages/monitor/lib/metrics.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1462 fix animation for dialogs that have the data when mounted
  frontend/src/components/ControlPlaneHighAvailability/ManageControlPlaneHighAvailability.vue
  frontend/src/components/ShootDns/ManageDns.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1465 [master] Do not use lookbehind regex assertions
  frontend/src/store/modules/shoots/helper.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
