Repository gardener/dashboard, pull requests merged in 2023-12, with the labels that each got.

#1642 Improve table column selection menu
  frontend/src/components/GTableColumnSelection.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1635 Fix: Show machine image description and hints
  frontend/src/components/ShootWorkers/GMachineImage.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1643 Replaced absolute links with relative
  docs/development/local-setup.md
  docs/operations/customization.md
  docs/usage/custom-fields.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1645 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/deployment.spec.js
  charts/gardener-dashboard/values.yaml
  docs/usage/terminal-shortcuts.md
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1651 Added Section on Rotating Project Secrets
  docs/usage/working-with-projects.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1633 Enhance Error Message Handling
  frontend/src/components/GCloudProfile.vue
  frontend/src/components/GPurpose.vue
  frontend/src/components/GPurposeConfiguration.vue
  frontend/src/components/GShootActionDeleteCluster.vue
  frontend/src/components/GShootActionDialog.vue
  frontend/src/components/GTerminalSettings.vue
  frontend/src/components/GTerminalTarget.vue
  frontend/src/components/GTimeTextField.vue
  frontend/src/components/GWildcardSelect.vue
  frontend/src/components/Members/GMemberDialog.vue
  frontend/src/components/NewShoot/GNewShootDetails.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/components/Secrets/GSecretDialog.vue
  frontend/src/components/Secrets/GSecretDialogAlicloud.vue
  frontend/src/components/Secrets/GSecretDialogAws.vue
  frontend/src/components/Secrets/GSecretDialogAzure.vue
  frontend/src/components/Secrets/GSecretDialogCloudflare.vue
  frontend/src/components/Secrets/GSecretDialogGcp.vue
  frontend/src/components/Secrets/GSecretDialogGeneric.vue
  frontend/src/components/Secrets/GSecretDialogHCloud.vue
  frontend/src/components/Secrets/GSecretDialogInfoblox.vue
  frontend/src/components/Secrets/GSecretDialogMetal.vue
  frontend/src/components/Secrets/GSecretDialogNetlify.vue
  frontend/src/components/Secrets/GSecretDialogOpenstack.vue
  frontend/src/components/Secrets/GSecretDialogVSphere.vue
  frontend/src/components/Secrets/GSelectSecret.vue
  frontend/src/components/ShootDns/GDnsConfiguration.vue
  frontend/src/components/ShootDns/GDnsProviderRow.vue
  frontend/src/components/ShootDns/GManageDns.vue
  frontend/src/components/ShootHibernation/GHibernationConfiguration.vue
  frontend/src/components/ShootHibernation/GHibernationScheduleEvent.vue
  frontend/src/components/ShootMaintenance/GMaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/GMaintenanceTime.vue
  frontend/src/components/ShootVersion/GShootVersion.vue
  frontend/src/components/ShootVersion/GShootVersionUpdate.vue
  frontend/src/components/ShootWorkers/GContainerRuntime.vue
  frontend/src/components/ShootWorkers/GMachineImage.vue
  frontend/src/components/ShootWorkers/GMachineType.vue
  frontend/src/components/ShootWorkers/GVolumeType.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/components/dialogs/GActionButtonDialog.vue
  frontend/src/components/dialogs/GCreateTerminalSessionDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/components/dialogs/GTerminalSettingsDialog.vue
  frontend/src/components/editable/GEditableAccount.vue
  frontend/src/components/editable/GEditableText.vue
  frontend/src/utils/index.js
  frontend/src/utils/validators.js
  frontend/src/views/GAdministration.vue
  frontend/src/views/GNewShoot.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion, area/ipcei

#1656 Added configuration parameter that specifies the maximum size of the request body
  backend/lib/api.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1658 Fix: k8s dashboard not shown on details page
  backend/lib/services/shoots.js
  frontend/src/components/GShootListRow.vue
  frontend/src/components/ShootDetails/GShootAccessCard.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1657 Fix garden terminal host for managed-seeds
  backend/lib/services/terminals/index.js
  backend/lib/services/terminals/utils.js
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
  backend/test/acceptance/api.terminals.spec.js
  backend/test/services.terminals.spec.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1660 Fix client side validation error into view
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1661 Do not fetch shoots twice
  .vscode/settings.json
  frontend/src/store/shoot/helper.js
  frontend/src/store/shoot/index.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1663 [hotfix-1.71] Fixed navigation to the all projects list for non-admin users
  backend/__fixtures__/shoots.js
  backend/lib/services/shoots.js
  backend/lib/utils/index.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  backend/test/utils.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
Labels: needs/ok-to-test

#1664 [master] Fixed navigation to the all projects list for non-admin users
  backend/__fixtures__/shoots.js
  backend/lib/services/shoots.js
  backend/lib/utils/index.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  backend/test/utils.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
Labels: needs/ok-to-test

#1667 fix link to Azure permission documentation
  frontend/src/components/Secrets/GSecretDialogAzure.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1668 Drop support for basic auth
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/store/shoot/helper.js
  frontend/src/store/shoot/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1669 Enh/remove deprecated annotations
  backend/lib/services/members/SubjectList.js
  frontend/src/components/GAccountAvatar.vue
  frontend/src/mixins/shootItem.js
  frontend/src/utils/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
