Repository gardener/dashboard, pull requests merged in 2024-01, with the labels that each got.

#1672 Fixed version update selection
  frontend/src/components/ShootVersion/GShootVersionUpdate.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1670 Add rule `arrow-parens` to eslint
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/components/GShootEditor.vue
  frontend/src/components/GTimeTextField.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/components/Secrets/GSecretDialog.vue
  frontend/src/components/Secrets/GSecretDialogGcp.vue
  frontend/src/components/ShootDetails/GShootDetailsCard.vue
  frontend/src/components/ShootTickets/GTicketLabel.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/store/cloudProfile/index.js
  frontend/src/utils/shootEditorCompletions.js
  frontend/src/utils/validators.js
  frontend/src/utils/wildcard.js
  frontend/src/views/GSecrets.vue
  frontend/src/views/GShootItemEditor.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1666 Add ability to retreive adminkubeconfig to dashboard
  backend/lib/routes/shoots.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/src/components/GActionButton.vue
  frontend/src/components/GCopyBtn.vue
  frontend/src/components/GGardenctlConfigExample.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GShootMessageDetails.vue
  frontend/src/components/GShootSeedName.vue
  frontend/src/components/GTextRouterLink.vue
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/components/ShootDetails/GShootAdminKubeconfig.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/components/ShootDetails/GShootKubeconfig.vue
  frontend/src/components/ShootDns/GDnsProvider.vue
  frontend/src/components/ShootMessages/GNoHibernationScheduleMessage.vue
  frontend/src/composables/useApi/api.js
  frontend/src/composables/useShootAdminKubeconfig.js
  frontend/src/store/config.js
  frontend/src/store/localStorage.js
  frontend/src/views/GAdministration.vue
  frontend/src/views/GSettings.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test

#1673 Updated the kubeconfig documentation
  docs/README.md
  docs/usage/automated-resource-management.md
  docs/usage/project-operations.md
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1677 Added seed conditions to known conditions
  frontend/src/store/config.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1678 Fix typo in "no supported cloud profile" warning
  frontend/src/views/GSecrets.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#1675 Do not show hidden github comments
  .pnp.cjs
  .yarn/cache/@octokit-auth-token-npm-2.5.0-a1c6ffb640-45949296c0.zip
  .yarn/cache/@octokit-auth-token-npm-4.0.0-9ad78a752f-d78f4dc48b.zip
  .yarn/cache/@octokit-core-npm-3.6.0-1273c50268-f811601290.zip
  .yarn/cache/@octokit-core-npm-5.0.2-3dc365a695-9ce060d615.zip
  .yarn/cache/@octokit-endpoint-npm-6.0.12-d467db27fd-b48b29940a.zip
  .yarn/cache/@octokit-graphql-npm-4.8.0-83d118b4da-f68afe53f6.zip
  .yarn/cache/@octokit-graphql-npm-7.0.2-b5522f5b29-05a752c4c2.zip
  .yarn/cache/@octokit-openapi-types-npm-12.11.0-cc40f04bc8-8a7d4bd628.zip
  .yarn/cache/@octokit-openapi-types-npm-19.0.0-064193076f-9a8125ab4e.zip
  .yarn/cache/@octokit-openapi-types-npm-19.1.0-bd98fe458b-9d1b188741.zip
  .yarn/cache/@octokit-plugin-paginate-graphql-npm-4.0.0-e66930154f-368121d74f.zip
  .yarn/cache/@octokit-plugin-paginate-rest-npm-2.21.3-82d2ad1bba-acf31de2ba.zip
  .yarn/cache/@octokit-plugin-paginate-rest-npm-9.1.5-9d33eaf13c-ee5bc62e31.zip
  .yarn/cache/@octokit-plugin-request-log-npm-1.0.4-9ab5a2f888-2086db0005.zip
  .yarn/cache/@octokit-plugin-request-log-npm-4.0.0-49c2f6ee8b-2a8a661964.zip
  .yarn/cache/@octokit-plugin-rest-endpoint-methods-npm-10.2.0-d127ce1d53-3209688bf5.zip
  .yarn/cache/@octokit-plugin-rest-endpoint-methods-npm-5.16.2-f54316c392-30fcc50c33.zip
  .yarn/cache/@octokit-request-error-npm-2.1.0-51ac624306-baec2b5700.zip
  .yarn/cache/@octokit-request-npm-5.6.3-25a5f5382d-c0b4542eb4.zip
  .yarn/cache/@octokit-request-npm-8.1.2-e350fab15b-77b9221916.zip
  .yarn/cache/@octokit-request-npm-8.1.6-60f1cd7aad-df90204586.zip
  .yarn/cache/@octokit-rest-npm-18.12.0-f250ac8e5e-c18bd6676a.zip
  .yarn/cache/@octokit-types-npm-12.0.0-b74b3121ec-ad55e13cbe.zip
  .yarn/cache/@octokit-types-npm-12.4.0-52c6e4e06b-17bca450ef.zip
  .yarn/cache/@octokit-types-npm-6.41.0-5788f32962-fd6f75e0b1.zip
  .yarn/cache/vite-npm-4.4.9-e845c1bbf8-c511024cea.zip
  backend/__mocks__/@octokit/core.js
  backend/__mocks__/@octokit/rest.js
  backend/lib/github/index.js
  backend/lib/github/octokit.js
  backend/package.json
  backend/test/acceptance/api.tickets.spec.js
  backend/test/acceptance/io.spec.js
  backend/test/github.spec.js
  frontend/src/components/GTicketsCard.vue
  frontend/src/components/ShootTickets/GTicket.vue
  yarn.lock
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#1679 Update `Connect Kubectl` documentation
  docs/images/copy-target-cluster-command.png
  docs/images/download-garden-cluster-kubeconfig.png
  docs/usage/connect-kubectl.md
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1681 use variant=tonal instead of outlined
  frontend/src/components/ControlPlaneHighAvailability/GControlPlaneHighAvailabilityTag.vue
  frontend/src/components/ControlPlaneHighAvailability/GManageControlPlaneHighAvailability.vue
  frontend/src/components/GCredentialTile.vue
  frontend/src/components/GMessage.vue
  frontend/src/components/GPurposeTag.vue
  frontend/src/components/GShootActionRotateCredentials.vue
  frontend/src/components/GShootCustomField.vue
  frontend/src/components/GStatusTag.vue
  frontend/src/components/GTerminalSettings.vue
  frontend/src/components/GTerminalShortcut.vue
  frontend/src/components/GTerminalTarget.vue
  frontend/src/components/GWildcardSelect.vue
  frontend/src/components/Members/GAccountRoles.vue
  frontend/src/components/Members/GMemberDialog.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionChips.vue
  frontend/src/components/ShootDetails/GShootAdminKubeconfig.vue
  frontend/src/components/ShootDetails/GShootDetailsCard.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/components/ShootDns/GDnsProvider.vue
  frontend/src/components/ShootDns/GDnsProviderRow.vue
  frontend/src/components/ShootHibernation/GHibernationScheduleEvent.vue
  frontend/src/components/ShootHibernation/GManageHibernationSchedule.vue
  frontend/src/components/ShootMaintenance/GShootActionMaintenanceStart.vue
  frontend/src/components/ShootVersion/GShootVersion.vue
  frontend/src/components/ShootVersion/GShootVersionUpdate.vue
  frontend/src/components/ShootWorkers/GManageWorkers.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
  frontend/src/components/ShootWorkers/GWorkerGroups.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/components/dialogs/GUnverifiedTerminalShortcutsDialog.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1687 Fix highlight selected project on key down
  frontend/src/components/GMainNavigation.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1685 Ensure `timeoutId` is defined before it is accessed in `useCustomColor`
  frontend/__tests__/composables/useCustomColors.spec.js
  frontend/src/composables/useCustomColors.js
  frontend/src/store/shoot/index.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1686 Fixed member validation
  frontend/src/components/Members/GMemberDialog.vue
  frontend/src/plugins/vuetify.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1688 Renamed and aligned admin kubeconfig
  frontend/src/components/ShootDetails/GShootAdminKubeconfig.vue
  frontend/src/views/GSettings.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1683 Kubernetes Version Update Improvements
  frontend/src/components/ShootVersion/GShootVersion.vue
  frontend/src/components/ShootVersion/GShootVersionUpdate.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1689 The author of a github comment can be `null`
  backend/lib/github/index.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1690 set namespace query param
  frontend/src/components/GGardenctlConfigExample.vue
  frontend/src/components/GGardenloginInfo.vue
  frontend/src/components/ShootDetails/GShootAdminKubeconfig.vue
  frontend/src/components/ShootDetails/GShootKubeconfig.vue
  frontend/src/views/GAdministration.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1692 fix extra spacing
  frontend/src/components/GTimeString.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1691 Fixes the `popoverKey` of the `GShootMessages` component
  frontend/src/components/ShootMessages/GShootMessages.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1693 Show update arrow only for supported versions
  frontend/src/components/ShootVersion/GShootVersion.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1696 set grayscale inside GVendorIcon component
  frontend/src/components/GMainNavigation.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureCard.vue
  frontend/src/components/NewShoot/GNewShootSelectInfrastructure.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1697 Streamlined Action Dialogs
  frontend/src/components/ControlPlaneHighAvailability/GControlPlaneHighAvailabilityConfiguration.vue
  frontend/src/components/GActionButton.vue
  frontend/src/components/GCopyBtn.vue
  frontend/src/components/GPurpose.vue
  frontend/src/components/GPurposeConfiguration.vue
  frontend/src/components/GReconcileStart.vue
  frontend/src/components/GResourceQuotaHelp.vue
  frontend/src/components/GSeedConfiguration.vue
  frontend/src/components/GShootActionButton.vue
  frontend/src/components/GShootActionDeleteCluster.vue
  frontend/src/components/GShootActionDialog.vue
  frontend/src/components/GShootActionReconcileStart.vue
  frontend/src/components/GShootActionRotateCredentials.vue
  frontend/src/components/GShootListRowActions.vue
  frontend/src/components/GStaticTokenKubeconfigConfiguration.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionsConfiguration.vue
  frontend/src/components/ShootAddons/GAddonConfiguration.vue
  frontend/src/components/ShootDetails/GShootLifecycleCard.vue
  frontend/src/components/ShootDns/GDnsConfiguration.vue
  frontend/src/components/ShootHibernation/GHibernationConfiguration.vue
  frontend/src/components/ShootHibernation/GShootActionChangeHibernation.vue
  frontend/src/components/ShootMaintenance/GMaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/GShootActionMaintenanceStart.vue
  frontend/src/components/ShootVersion/GShootVersion.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/dialogs/GActionButtonDialog.vue
  frontend/src/components/dialogs/GConfirmDialog.vue
  frontend/src/components/dialogs/GCreateTerminalSessionDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/GInfoDialog.vue
  frontend/src/components/dialogs/GTerminalSettingsDialog.vue
  frontend/src/components/dialogs/GUnverifiedTerminalShortcutsDialog.vue
  frontend/src/components/dialogs/GWebterminalServiceAccountDialog.vue
  frontend/src/mixins/shootItem.js
  frontend/src/sass/main.scss
  frontend/src/views/GAdministration.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test

#1700 Add support for `ironcore` infrastructure
  frontend/src/assets/ironcore.svg
  frontend/src/components/GVendorIcon.vue
  frontend/src/store/cloudProfile/index.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test
