Repository gardener/dashboard, pull requests merged in 2024-07, with the labels that each got.

#1950 Avoid side effects using `trimObjectMetadata`
  backend/lib/io.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1888 Configure extension DNS settings in the `spec.extensions` section
  backend/lib/routes/shoots.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  frontend/__tests__/composables/__snapshots__/useShootContext.spec.js.snap
  frontend/__tests__/composables/__snapshots__/useShootDns.spec.js.snap
  frontend/__tests__/composables/useShootContext.spec.js
  frontend/__tests__/composables/useShootDns.spec.js
  frontend/src/assets/rfc2136.svg
  frontend/src/components/GVendorIcon.vue
  frontend/src/components/Secrets/GSecretDetailsItemContent.vue
  frontend/src/components/Secrets/GSecretDialogDDns.vue
  frontend/src/components/Secrets/GSecretDialogWrapper.vue
  frontend/src/components/Secrets/GSelectSecret.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/components/ShootDns/GDnsConfiguration.vue
  frontend/src/components/ShootDns/GDnsProvider.vue
  frontend/src/components/ShootDns/GDnsProviderRow.vue
  frontend/src/components/ShootDns/GManageDns.vue
  frontend/src/components/ShootHibernation/GHibernationScheduleEvent.vue
  frontend/src/composables/useApi/api.js
  frontend/src/composables/useShootContext.js
  frontend/src/composables/useShootDns.js
  frontend/src/composables/useShootItem.js
  frontend/src/composables/useShootSpec.js
  frontend/src/lodash.js
  frontend/src/sass/main.scss
  frontend/src/store/gardenerExtension.js
  frontend/src/utils/validators.js
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test, area/ipcei

#1964 Set correct focus for login button
  frontend/src/layouts/GLogin.vue
  frontend/src/utils/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1952 GShootList: Reflect search query in URL
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1969 Fixed remove last dns provider
  frontend/src/components/ShootDns/GDnsConfiguration.vue
  frontend/src/composables/useShootDns.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1978 Replace `@braintree/sanitize-url` with an own simple implementation
  .pnp.cjs
  .yarn/cache/@braintree-sanitize-url-npm-7.0.1-302de011e8-d849b93f49.zip
  frontend/__tests__/composables/useSanatizeUrl.spec.js
  frontend/package.json
  frontend/src/composables/useSanitizeUrl.js
  yarn.lock
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1946 Refactor Project Services and Routes
  backend/lib/cache/index.js
  backend/lib/routes/index.js
  backend/lib/routes/projects.js
  backend/lib/security/index.js
  backend/lib/security/jose.js
  backend/lib/services/projects.js
  backend/lib/utils/index.js
  backend/test/__snapshots__/services.projects.spec.js.snap
  backend/test/acceptance/__snapshots__/api.projects.spec.js.snap
  backend/test/acceptance/api.projects.spec.js
  backend/test/services.projects.spec.js
  backend/test/utils.spec.js
  frontend/__tests__/stores/shoot.spec.js
  frontend/src/components/GGardenctlConfigExample.vue
  frontend/src/components/GMainNavigation.vue
  frontend/src/components/GNotReadyProjectWarning.vue
  frontend/src/components/GStaleProjectWarning.vue
  frontend/src/components/Secrets/GSelectSecret.vue
  frontend/src/components/ShootDetails/GShootAdminKubeconfig.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/components/editable/GEditableText.vue
  frontend/src/composables/useApi/api.js
  frontend/src/composables/useProjectContext.js
  frontend/src/composables/useProjectCostObject.js
  frontend/src/composables/useProjectItem.js
  frontend/src/composables/useProjectShootCustomFields/index.js
  frontend/src/store/project.js
  frontend/src/store/socket/index.js
  frontend/src/utils/index.js
  frontend/src/views/GAccount.vue
  frontend/src/views/GAdministration.vue
  frontend/src/views/GMembers.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion, area/ipcei

#1982 Add YAML line selection highlighting in GShootEditor
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/composables/useEditorLineHighlighter.js
  frontend/src/composables/useShootEditor/index.js
  frontend/src/sass/main.scss
Labels: reviewed/lgtm, size/m, needs/ok-to-test, area/ipcei

#1999 Fixed worker group zone configuration for existing azure clusters
  frontend/src/composables/useShootContext.js
  frontend/src/composables/useShootHelper.js
  frontend/src/utils/index.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1983 Cleanup GShootStatus component
  frontend/src/components/GShootStatus.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test, area/ipcei

#1998 Fixed broken links in Project Operations
  docs/usage/project-operations.md
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#2003 [hotfix-1.76] Fixed worker group zone configuration for existing azure clusters
  frontend/src/composables/useShootContext.js
  frontend/src/composables/useShootHelper.js
  frontend/src/utils/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test
