Repository gardener/dashboard, pull requests merged in 2024-04, with the labels that each got.

#1758 Align Version and Worker Chips
  frontend/src/components/GSeedConfiguration.vue
  frontend/src/components/GShootActionDeleteCluster.vue
  frontend/src/components/GShootActionForceDelete.vue
  frontend/src/components/GShootActionReconcileStart.vue
  frontend/src/components/GShootActionRotateCredentials.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GShootListRowActions.vue
  frontend/src/components/ShootDetails/GShootDetailsCard.vue
  frontend/src/components/ShootHibernation/GShootActionChangeHibernation.vue
  frontend/src/components/ShootMaintenance/GShootActionMaintenanceStart.vue
  frontend/src/components/ShootVersion/GShootVersion.vue
  frontend/src/components/ShootVersion/GShootVersionChip.vue
  frontend/src/components/ShootVersion/GShootVersionConfiguration.vue
  frontend/src/components/ShootVersion/GShootVersionUpdate.vue
  frontend/src/components/ShootWorkers/GMachineImage.vue
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
  frontend/src/components/ShootWorkers/GWorkerGroups.vue
  frontend/src/mixins/shootItem.js
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#1752 Show route information in window title
  frontend/src/App.vue
  frontend/src/router/routes.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test, area/ipcei

#1800 Fix list indexing in doc
  docs/development/local-setup.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1819 renovate: Ignore `eslint` major updates
  .github/renovate.json5
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1810 `Terminal`: show last error description on timeout
  backend/lib/services/projects.js
  backend/lib/services/terminals/index.js
  frontend/src/components/GTerminal.vue
  packages/kube-client/__tests__/http-client.test.js
  packages/kube-client/lib/HttpClient.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1824 [master] Ticket title should contain project name
  charts/gardener-dashboard/values.yaml
  frontend/src/components/GTicketsCard.vue
Labels: kind/bug, reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1836 Cleanup: Remove `pragma: whitelist secret` comments
  backend/lib/config/gardener.js
  backend/lib/services/cloudProviderSecrets.js
Labels: needs/review, size/xs, needs/ok-to-test

#1830 [hotfix-1.74] Automated cherry pick of #1824: [master] Ticket title should contain project name
  charts/gardener-dashboard/values.yaml
  frontend/src/components/GTicketsCard.vue
Labels: kind/bug, reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1823 Create `Lease` object during runtime
  backend/lib/github/webhook/handler.js
  backend/test/github.spec.js
  charts/__tests__/gardener-dashboard/application/dashboard/__snapshots__/lease-github-webhook.spec.js.snap
  charts/__tests__/gardener-dashboard/application/dashboard/__snapshots__/role.spec.js.snap
  charts/__tests__/gardener-dashboard/application/dashboard/lease-github-webhook.spec.js
  charts/gardener-dashboard/charts/application/templates/dashboard/lease-github-webhook.yaml
  charts/gardener-dashboard/charts/application/templates/dashboard/role.yaml
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1835 Make `oidc.clientSecret` optional
  backend/__fixtures__/config.js
  backend/lib/config/gardener.js
  charts/__fixtures__/gardener-dashboard.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/secrets.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/deployment.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/secrets.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
  charts/gardener-dashboard/charts/runtime/templates/dashboard/secret-oidc.yaml
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1831 Add hack/cherry-pick-pull.sh
  docs/README.md
  docs/development/process.md
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, reviewed/lgtm, size/l, reviewed/ok-to-test, needs/ok-to-test

#1822 Promote `experimentalUseWatchCacheForListShoots` to stable
  backend/__fixtures__/config.js
  backend/lib/routes/shoots.js
  backend/lib/services/shoots.js
  backend/lib/utils/index.js
  backend/test/acceptance/__snapshots__/api.cloudProviderSecrets.spec.js.snap
  backend/test/acceptance/__snapshots__/api.projects.spec.js.snap
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.cloudProviderSecrets.spec.js
  backend/test/acceptance/api.projects.spec.js
  backend/test/acceptance/api.shoots.spec.js
  backend/test/utils.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
Labels: size/xl, needs/ok-to-test, needs/second-opinion
