Repository gardener/dashboard, pull requests merged in 2024-11, with the labels that each got.

#2164 Remove fallback to read cluster ca Secret
  backend/lib/services/shoots.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2155 Use shared composable instead of event propagation to distribute state
  frontend/src/components/GShootListActions.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/composables/useShootAction.js
  frontend/src/utils/validators.js
  frontend/src/views/GShootList.vue
Labels: size/m, reviewed/ok-to-test, needs/review, needs/second-opinion

#2163 Adapt to new shoot access restriction configurations in `CloudProfile`, `Seed`, and `Shoot` APIs
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  docs/operations/access-restrictions.md
  frontend/__fixtures__/config.js
  frontend/__tests__/composables/useShootAccessRestrictions.spec.js
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictions.vue
  frontend/src/composables/useShootAccessRestrictions/index.js
  frontend/src/store/cloudProfile/index.js
Labels: size/l, needs/ok-to-test, needs/rebase, needs/second-opinion

#2169 Terminal: Drop usage of deprecated `credential.secretRef` field
  backend/__fixtures__/config.js
  backend/__fixtures__/secrets.js
  backend/__fixtures__/seeds.js
  backend/__fixtures__/shoots.js
  backend/__fixtures__/terminals.js
  backend/lib/services/terminals/index.js
  backend/lib/services/terminals/utils.js
  backend/test/acceptance/__snapshots__/api.cloudprofiles.spec.js.snap
  backend/test/acceptance/__snapshots__/api.seeds.spec.js.snap
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
  backend/test/acceptance/api.terminals.spec.js
  backend/test/services.terminals.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  docs/operations/webterminals.md
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#2176 Fix readonly editor
  frontend/src/composables/useShootEditor/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2178 Fix alertmanager URL
  frontend/src/components/GClusterMetrics.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2141 Removed dashboard specific secretbinding labels
  backend/lib/services/cloudProviderSecrets.js
  backend/lib/services/cloudprofiles.js
  backend/test/acceptance/__snapshots__/api.cloudProviderSecrets.spec.js.snap
  backend/test/acceptance/__snapshots__/api.cloudprofiles.spec.js.snap
  backend/test/acceptance/api.cloudProviderSecrets.spec.js
  frontend/__fixtures__/cloudprofiles.js
  frontend/__fixtures__/secrets.js
  frontend/__tests__/composables/__snapshots__/useShootContext.spec.js.snap
  frontend/__tests__/composables/useShootContext.spec.js
  frontend/src/components/GForceDeleteCluster.vue
  frontend/src/components/GSeedConfiguration.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GTicketsCard.vue
  frontend/src/components/GVendor.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureCard.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/components/NewShoot/GNewShootSelectInfrastructure.vue
  frontend/src/components/Secrets/GSecretDetailsItemContent.vue
  frontend/src/components/Secrets/GSecretDialog.vue
  frontend/src/components/Secrets/GSecretDialogAlicloud.vue
  frontend/src/components/Secrets/GSecretDialogAws.vue
  frontend/src/components/Secrets/GSecretDialogAzure.vue
  frontend/src/components/Secrets/GSecretDialogGcp.vue
  frontend/src/components/Secrets/GSecretDialogGeneric.vue
  frontend/src/components/Secrets/GSecretDialogOpenstack.vue
  frontend/src/components/Secrets/GSecretDialogWrapper.vue
  frontend/src/components/Secrets/GSecretRowDns.vue
  frontend/src/components/Secrets/GSecretRowInfra.vue
  frontend/src/components/Secrets/GSelectSecret.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/components/ShootDns/GDnsProviderRow.vue
  frontend/src/components/ShootDns/GManageDns.vue
  frontend/src/components/ShootWorkers/GVolumeType.vue
  frontend/src/composables/useSecretList.js
  frontend/src/composables/useShootContext.js
  frontend/src/composables/useShootDns.js
  frontend/src/composables/useShootHelper.js
  frontend/src/composables/useShootItem.js
  frontend/src/composables/useShootSpec.js
  frontend/src/store/cloudProfile/index.js
  frontend/src/store/secret.js
  frontend/src/utils/shoot.js
  frontend/src/views/GNewShoot.vue
  frontend/src/views/GSecrets.vue
Labels: reviewed/lgtm, size/xl, needs/ok-to-test

#2180 Fix bug on theme change
  frontend/src/composables/useShootEditor/index.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#2171 Drop support of static token kubeconfig
  backend/__fixtures__/secrets.js
  backend/lib/routes/shoots.js
  backend/lib/services/shoots.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  frontend/__tests__/components/GNewShootDetails.spec.js
  frontend/__tests__/components/GShootCredentialRotation.spec.js
  frontend/__tests__/composables/__snapshots__/useShootContext.spec.js.snap
  frontend/__tests__/composables/useShootStatusCredentialRotation.spec.js
  frontend/src/components/GShootActionRotateCredentials.vue
  frontend/src/components/GStaticTokenKubeconfigConfiguration.vue
  frontend/src/components/GStaticTokenKubeconfigSwitch.vue
  frontend/src/components/NewShoot/GNewShootDetails.vue
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/components/ShootDetails/GShootCredentialRotationCard.vue
  frontend/src/components/ShootDetails/GShootKubeconfig.vue
  frontend/src/composables/useApi/api.js
  frontend/src/composables/useShootContext.js
  frontend/src/composables/useShootItem.js
  frontend/src/composables/useShootSpec.js
  frontend/src/composables/useShootStatusCredentialRotation.js
Labels: reviewed/lgtm, size/xl, needs/ok-to-test

#2193 Fix: `ul` must not be a child of `p`
  frontend/src/components/Secrets/GSecretDialogGcp.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2190 Minor improvements of Codemirror 6 migration
  frontend/__tests__/composables/useShootEditor.spec.js
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/composables/useEditorLineHighlighter.js
  frontend/src/composables/useEditorWhitespace.js
  frontend/src/composables/useShootEditor/helper.js
  frontend/src/composables/useShootEditor/index.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#2196 Handle removal of legacy access restriction
  frontend/__fixtures__/cloudprofiles.js
  frontend/__fixtures__/config.js
  frontend/src/composables/useShootAccessRestrictions/index.js
  frontend/src/store/config.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#2202 Use a polling watcher instead of chokidar
  .pnp.cjs
  .yarn/cache/@eslint-community-eslint-utils-npm-4.4.0-d1791bd5a3-7e559c4ce5.zip
  .yarn/cache/@eslint-community-regexpp-npm-4.11.1-37bbb67aaa-fbcc1cb65e.zip
  .yarn/cache/@vue-compiler-core-npm-3.5.12-ec7e993ccc-7f004b9633.zip
  .yarn/cache/@vue-compiler-dom-npm-3.5.12-2c6fcbab3c-48a67cd28c.zip
  .yarn/cache/@vue-compiler-ssr-npm-3.5.12-e1e40560ca-8a8fc4e205.zip
  .yarn/cache/@vue-server-renderer-npm-3.5.12-3ad333df56-d9f25f165c.zip
  .yarn/cache/@vue-shared-npm-3.5.12-70fd2bd5d7-48f94406c4.zip
  .yarn/cache/globals-npm-15.11.0-336de1c0c2-861e39bb6b.zip
  .yarn/cache/picocolors-npm-1.1.0-ea12a640bd-86946f6032.zip
  .yarn/cache/postcss-npm-8.4.47-2f4d4be1fa-929f68b508.zip
  packages/kube-config/__tests__/client-config.test.js
  packages/kube-config/__tests__/kube-config.test.js
  packages/kube-config/__tests__/polling-watcher.test.js
  packages/kube-config/__tests__/watcher.test.js
  packages/kube-config/lib/ClientConfig.js
  packages/kube-config/lib/PollingWatcher.js
  packages/kube-config/lib/Watcher.js
  packages/kube-config/package.json
  yarn.lock
Labels: size/xl, needs/ok-to-test, needs/second-opinion
