Repository gardener/dashboard, pull requests merged in 2024-09, with the labels that each got.

#2048 Fixed worker zone network management for existing shoots
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/composables/useShootContext.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#2031 Respect purpose === evaluation for add-ons
  frontend/src/components/GPurpose.vue
  frontend/src/components/ShootAddons/GAddonConfiguration.vue
  frontend/src/components/ShootAddons/GManageAddons.vue
  frontend/src/components/ShootDetails/GShootDetailsCard.vue
  frontend/src/composables/useShootHelper.js
  frontend/src/utils/index.js
  frontend/src/views/GNewShoot.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#2090 Fix vite warning
  frontend/src/components/Secrets/GSecretDialogNetlify.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2080 Fix lint error
  frontend/src/components/ShootWorkers/GMachineType.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2077 Hide SSH keypair rotation when SSH access disabled
  frontend/__tests__/components/GShootCredentialRotation.spec.js
  frontend/src/components/GShootActionRotateCredentials.vue
  frontend/src/components/ShootDetails/GShootCredentialRotationCard.vue
  frontend/src/composables/useShootItem.js
  frontend/src/composables/useShootSpec.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#2076 Fix issues with hibernation schedule dialog
  frontend/src/components/ShootHibernation/GHibernationScheduleEvent.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2098 Allow to trigger reconcile for clusters that are marked for deletion
  frontend/src/components/GShootActionReconcileStart.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2102 Support Multiple Cost Object Types in Configuration
  backend/__fixtures__/projects.js
  backend/lib/routes/config.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/configmap.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/__fixtures__/config.js
  frontend/src/components/GProjectCostObject.vue
  frontend/src/components/GProjectCostObjectConfiguration.vue
  frontend/src/components/Secrets/GSelectSecret.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/composables/useProjectContext.js
  frontend/src/composables/useProjectCostObject.js
  frontend/src/composables/useProjectItem.js
  frontend/src/store/config.js
  frontend/src/views/GAdministration.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#2079 Enhance Migration Process: Consider All Seeds and Warn for Provider Mismatch
  frontend/src/components/GSeedConfiguration.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2034 Support Azure cloud configuration for DNS Secrets
  frontend/src/components/Secrets/GSecretDialogAzure.vue
  frontend/src/utils/validators.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1991 Collapse ShootList Columns
  frontend/src/components/GCodeBlock.vue
  frontend/src/components/GCollapsibleItems.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GShootStatus.vue
  frontend/src/components/GVendor.vue
  frontend/src/components/Secrets/GSecretDialogAlicloud.vue
  frontend/src/components/Secrets/GSecretDialogAws.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionChip.vue
  frontend/src/components/ShootDetails/GShootDetailsCard.vue
  frontend/src/components/ShootTickets/GTicket.vue
  frontend/src/components/ShootTickets/GTicketLabel.vue
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
  frontend/src/components/ShootWorkers/GWorkerGroups.vue
  frontend/src/components/ShootWorkers/GWorkerlessChip.vue
  frontend/src/store/shoot/helper.js
  frontend/src/views/GSecrets.vue
  frontend/src/views/GShootList.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion
