Repository gardener/dashboard, pull requests merged in 2024-06, with the labels that each got.

#1898 [hotfix-1.75] Do not fail if tickets could not be fetched
  frontend/src/store/shoot/index.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1875 Remove docforge from repo
  .ci/check-docforge
  .docforge/manifest.yaml
  .reuse/dep5
  .vscode/settings.json
  Makefile
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1887 Show all constraints not in the condition `status != "True"`
  frontend/__tests__/components/GStatusTags.spec.js
  frontend/src/components/GStatusTags.vue
  frontend/src/composables/useShootStatus.js
  frontend/src/store/config.js
  frontend/src/store/shoot/helper.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test, area/ipcei

#1905 [hotfix-1.74] Do not fail if tickets could not be fetched
  frontend/src/store/shoot/index.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1899 Display OIDC observability URLs
  backend/__fixtures__/auth.js
  backend/__fixtures__/seeds.js
  backend/lib/services/authorization.js
  backend/lib/services/seeds.js
  backend/lib/services/shoots.js
  backend/lib/utils/index.js
  backend/test/acceptance/__snapshots__/api.seeds.spec.js.snap
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  charts/__tests__/gardener-dashboard/application/dashboard/__snapshots__/clusterrole.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/gardener-dashboard/charts/application/templates/dashboard/clusterrole.yaml
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/src/components/GClusterMetrics.vue
  frontend/src/components/GUsernamePasswordListTile.vue
  frontend/src/components/ShootDetails/GShootMonitoringCard.vue
  frontend/src/composables/useShootHelper.js
  frontend/src/composables/useShootInfo.js
  frontend/src/composables/useShootItem.js
  frontend/src/store/config.js
  frontend/src/store/shoot/shoot.js
Labels: size/l, needs/ok-to-test, needs/second-opinion, area/ipcei

#1894 Session management enhancements
  .gitignore
  .pnp.cjs
  .yarn/cache/@vitejs-plugin-basic-ssl-npm-1.1.0-cc457f595f-98aadf5c7f.zip
  .yarn/cache/cross-env-npm-7.0.3-96d81820f4-f3765c2574.zip
  backend/__fixtures__/config.js
  backend/lib/app.js
  backend/lib/security/constants.js
  backend/lib/security/index.js
  backend/package.json
  backend/test/acceptance/auth.spec.js
  backend/test/security.spec.js
  docs/development/local-setup.md
  frontend/.gitignore
  frontend/__tests__/components/GLogin.spec.js
  frontend/package.json
  frontend/src/layouts/GLogin.vue
  frontend/src/store/authn/helper.js
  frontend/vite.config.js
  scripts/vite-server-setup.sh
  yarn.lock
Labels: reviewed/lgtm, size/l, reviewed/ok-to-test, area/security, needs/ok-to-test, area/ipcei

#1889 Added support for DDNS / RFC2136
  backend/lib/services/cloudProviderSecrets.js
  frontend/src/assets/ddns.svg
  frontend/src/components/GVendorIcon.vue
  frontend/src/components/Secrets/GSecretDetailsItemContent.vue
  frontend/src/components/Secrets/GSecretDialog.vue
  frontend/src/components/Secrets/GSecretDialogAlicloud.vue
  frontend/src/components/Secrets/GSecretDialogAws.vue
  frontend/src/components/Secrets/GSecretDialogAzure.vue
  frontend/src/components/Secrets/GSecretDialogCloudflare.vue
  frontend/src/components/Secrets/GSecretDialogDDNS.vue
  frontend/src/components/Secrets/GSecretDialogGcp.vue
  frontend/src/components/Secrets/GSecretDialogHCloud.vue
  frontend/src/components/Secrets/GSecretDialogInfoblox.vue
  frontend/src/components/Secrets/GSecretDialogMetal.vue
  frontend/src/components/Secrets/GSecretDialogNetlify.vue
  frontend/src/components/Secrets/GSecretDialogOpenstack.vue
  frontend/src/components/Secrets/GSecretDialogVSphere.vue
  frontend/src/components/Secrets/GSecretDialogWrapper.vue
  frontend/src/store/gardenerExtension.js
Labels: size/xl, needs/ok-to-test, needs/second-opinion, area/ipcei

#1915 Clear `frozenUids` and reset `focusMode` on namespace change
  frontend/src/store/shoot/shoot.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1923 Adapt the debug and test scripts for `vscode-jest-runner` to be compatible with Vitest.
  .vscode/settings.json
  scripts/debug.cjs
  scripts/helper.cjs
  scripts/jest.cjs
  scripts/test.cjs
  scripts/yarn.cjs
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1928 Feedback to `enh/adapt_to_dns_changes`
  frontend/__tests__/composables/__snapshots__/useShootContext.spec.js.snap
  frontend/__tests__/composables/__snapshots__/useShootDns.spec.js.snap
  frontend/__tests__/composables/useShootContext.spec.js
  frontend/__tests__/composables/useShootDns.spec.js
  frontend/src/components/ShootDns/GDnsProviderRow.vue
  frontend/src/components/ShootDns/GManageDns.vue
  frontend/src/composables/useShootContext/index.js
  frontend/src/composables/useShootDns.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl

#1929 Fix project menu after vuetify update
  frontend/src/components/GMainNavigation.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1933 Cancel dialogs on `@keydown:esc`
  frontend/src/components/Members/GMemberDialog.vue
  frontend/src/components/Members/GMemberHelpDialog.vue
  frontend/src/components/Secrets/GSecretDialog.vue
  frontend/src/components/Secrets/GSecretDialogDelete.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/views/GMembers.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1934 Migrate GProjectDialog to script setup
  frontend/src/components/dialogs/GProjectDialog.vue
Labels: reviewed/lgtm, size/xl, needs/ok-to-test

#1937 Revert changes from PR 1933
  frontend/src/components/Members/GMemberDialog.vue
  frontend/src/components/Members/GMemberHelpDialog.vue
  frontend/src/components/Secrets/GSecretDialog.vue
  frontend/src/components/Secrets/GSecretDialogDelete.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/views/GMembers.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1926 Add Custom Field Configuration Editor for Shoot Clusters
  docs/images/custom-fields-1.png
  docs/images/custom-fields-2.png
  docs/images/custom-fields-3.png
  docs/images/custom-fields-4.png
  docs/images/custom-fields-5.png
  docs/images/custom-fields-6.png
  docs/images/custom-fields-7.png
  docs/usage/custom-fields.md
  frontend/__tests__/composables/__snapshots__/useProjectShootCustomFields.spec.js.snap
  frontend/__tests__/composables/useProjectShootCustomFields.spec.js
  frontend/__tests__/stores/project.spec.js
  frontend/__tests__/stores/shoot.spec.js
  frontend/src/components/GManageShootCustomFields.vue
  frontend/src/components/GShootCustomFieldsConfiguration.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/ShootDetails/GCustomFieldsCard.vue
  frontend/src/components/ShootDetails/GShootDetails.vue
  frontend/src/components/dialogs/GActionButtonDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/dialogs/GGenericActionButtonDialog.vue
  frontend/src/composables/helper.js
  frontend/src/composables/useProjectContext.js
  frontend/src/composables/useProjectItem.js
  frontend/src/composables/useProjectMetadata.js
  frontend/src/composables/useProjectShootCustomFields/helper.js
  frontend/src/composables/useProjectShootCustomFields/index.js
  frontend/src/composables/useScrollBar.js
  frontend/src/composables/useShootContext.js
  frontend/src/store/project.js
  frontend/src/store/shoot/helper.js
  frontend/src/store/shoot/shoot.js
  frontend/src/utils/index.js
  frontend/src/views/GAdministration.vue
  frontend/src/views/GShootItemPlaceholder.vue
  frontend/src/views/GShootList.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#1943 Fix issue when no costObject is defined
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/views/GAdministration.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1939 including the iss parameter in server code exchange
  backend/lib/security/index.js
  backend/test/acceptance/auth.spec.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
