Repository gardener/dashboard, pull requests merged in 2024-02, with the labels that each got.

#1702 Spinner: ensure interval is started only once
  frontend/src/lib/terminal.js
  frontend/src/router/routes.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1680 UI Enhancements
  frontend/src/components/ControlPlaneHighAvailability/GManageControlPlaneHighAvailability.vue
  frontend/src/components/GStaticTokenKubeconfigSwitch.vue
  frontend/src/components/ShootDns/GDnsProviderRow.vue
  frontend/src/components/ShootDns/GManageDns.vue
  frontend/src/components/ShootHibernation/GHibernationScheduleEvent.vue
  frontend/src/components/ShootHibernation/GManageHibernationSchedule.vue
  frontend/src/components/ShootWorkers/GManageWorkers.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/sass/main.scss
  frontend/src/views/GNewShoot.vue
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#1713 Removed force delete feature flag from dashboard configuration
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
  charts/gardener-dashboard/charts/runtime/templates/dashboard/configmap.yaml
  charts/gardener-dashboard/values.yaml
  frontend/__tests__/mixins/shootItem.spec.js
  frontend/src/mixins/shootItem.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1708 Support viewer to download `gardenlogin` kubeconfig by fetching cluster CA via `ConfigMap`
  backend/__fixtures__/configmaps.js
  backend/__fixtures__/secrets.js
  backend/lib/services/shoots.js
  backend/lib/services/terminals/index.js
  backend/test/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/test/acceptance/__snapshots__/api.terminals.spec.js.snap
  backend/test/acceptance/api.shoots.spec.js
  backend/test/acceptance/api.terminals.spec.js
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/components/ShootDetails/GShootAdminKubeconfig.vue
  frontend/src/components/ShootDetails/GShootDetails.vue
  frontend/src/components/ShootDetails/GShootKubeconfig.vue
  frontend/src/store/authz.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test, area/ipcei

#1714 Fix viewer handling for secret name
  frontend/src/components/GShootSecretName.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1715 rm tonal variant from worker cards
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1718 License and reuse adaptions
  LICENSE
  LICENSES/Apache-2.0.txt
  LICENSES/CC-BY-4.0.txt
  README.md
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test, area/ipcei

#1721 [master] Make storage size configuration more explicit
  frontend/src/components/ShootWorkers/GMachineType.vue
  frontend/src/components/ShootWorkers/GVolumeSizeInput.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/store/cloudProfile/index.js
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1722 [hotfix-1.73] Make storage size configuration more explicit
  frontend/src/components/ShootWorkers/GMachineType.vue
  frontend/src/components/ShootWorkers/GVolumeSizeInput.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/store/cloudProfile/index.js
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#1719 parse numerical abbreviations
  frontend/__tests__/utils/index.spec.js
  frontend/src/store/quota/helper.js
  frontend/src/utils/index.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test
