Repository gardener/dashboard, pull requests merged in 2024-12, with the labels that each got.

#2210 Added lint-sarif script to output lint results in SARIF format
  .pnp.cjs
  .yarn/cache/@eslint-eslintrc-npm-2.1.4-1ff4b5f908-32f67052b8.zip
  .yarn/cache/@eslint-js-npm-8.57.1-dec269f278-b489c474a3.zip
  .yarn/cache/@humanwhocodes-config-array-npm-0.13.0-843095a032-205c99e756.zip
  .yarn/cache/@humanwhocodes-object-schema-npm-2.0.3-4f0e508cd9-80520eabbf.zip
  .yarn/cache/@microsoft-eslint-formatter-sarif-npm-3.1.0-8a6a9d4f0b-c4052ea4f7.zip
  .yarn/cache/@ungap-structured-clone-npm-1.2.0-648f0b82e0-8209c937cb.zip
  .yarn/cache/doctrine-npm-3.0.0-c6f1615f04-c96bdccabe.zip
  .yarn/cache/eslint-npm-8.57.1-dd20287a5a-1fd3153308.zip
  .yarn/cache/file-entry-cache-npm-6.0.1-31965cf0af-58473e8a82.zip
  .yarn/cache/flat-cache-npm-3.2.0-9a887f084e-b76f611bd5.zip
  .yarn/cache/is-path-inside-npm-3.0.3-2ea0ef44fd-cf7d4ac35f.zip
  .yarn/cache/jschardet-npm-3.1.4-27880c8e9a-d72c724ff6.zip
  .yarn/cache/utf8-npm-3.0.0-7c39b5994a-675d008bab.zip
  Dockerfile
  backend/package.json
  frontend/package.json
  package.json
  packages/kube-client/package.json
  packages/kube-config/package.json
  packages/logger/package.json
  packages/monitor/package.json
  packages/request/package.json
  yarn.lock
Labels: reviewed/lgtm, size/l, reviewed/ok-to-test, needs/ok-to-test

#2206 Optimize CodeMirror Integration with Dynamic Imports
  frontend/__tests__/composables/useCodemirror.spec.js
  frontend/src/composables/useCodemirror/helper.js
  frontend/src/composables/useCodemirror/index.js
  frontend/src/composables/useEditorLineHighlighter.js
  frontend/src/composables/useShootEditor.js
  frontend/src/composables/useShootEditor/index.js
  frontend/src/composables/useShootSchemaDefinition.js
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#2212 Update yarn `prod-install` plugin sources
  .vscode/settings.json
  .yarn/plugins/plugin-prod-install.cjs
  .yarnrc.yml
  package.json
  scripts/plugin-prod-install.cjs
  scripts/update-prod-install.cjs
  yarn.lock
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test

#2225 fix: Use correct link for control plane high availability documentation
  frontend/src/components/ControlPlaneHighAvailability/GManageControlPlaneHighAvailability.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2221 fix: Use correct URL for shoot credentials rotation page
  frontend/src/components/GCredentialRotationHelp.vue
Labels: needs/review, size/xs, needs/ok-to-test

#2223 [openMFP] Move luigiContext and isInIframe to own composables
  frontend/src/App.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/composables/useIsInIframe.js
  frontend/src/composables/useOpenMFP.js
  frontend/src/composables/useProjectContext.js
  frontend/src/layouts/GDefault.vue
  frontend/src/router/guards.js
  frontend/src/store/app.js
  frontend/src/views/GAdministration.vue
  frontend/src/views/GProjectList.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test

#2230 [OpenMFP] Fix value access of ref
  frontend/src/composables/useProjectContext.js
  frontend/src/views/GAdministration.vue
  frontend/src/views/GProjectList.vue
Labels: reviewed/ok-to-test, needs/review, size/xs, needs/ok-to-test

#2235 Add duplicate dependency check to Docker build process
  .pnp.cjs
  .yarn/cache/@rollup-rollup-darwin-arm64-npm-4.22.4-1dd8e67109-10c0.zip
  .yarn/cache/@rollup-rollup-darwin-x64-npm-4.22.4-0da4fd74b2-10c0.zip
  .yarn/cache/@rollup-rollup-linux-arm64-musl-npm-4.22.4-66c26d2aea-10c0.zip
  .yarn/cache/@rollup-rollup-linux-x64-musl-npm-4.22.4-a4f79551cd-10c0.zip
  .yarn/cache/@types-estree-npm-1.0.5-5b7faed3b4-b3b0e33428.zip
  .yarn/cache/rollup-npm-4.22.4-bbb35d8edd-4c96b6e2e0.zip
  .yarnrc.yml
  Dockerfile
  yarn.lock
Labels: reviewed/lgtm, size/l, reviewed/ok-to-test, needs/ok-to-test

#2228 [OpenMFP] OpenFGA SelfSubjectRulesReview implementation
  backend/lib/openfga/index.js
  backend/lib/openfga/permissionMappings.js
  backend/lib/routes/user.js
  backend/lib/services/authorization.js
  backend/package.json
  frontend/src/composables/useApi/api.js
  frontend/src/composables/useOpenMFP.js
  frontend/src/router/guards.js
  frontend/src/router/routes.js
  frontend/src/store/authz.js
Labels: reviewed/lgtm, size/l, reviewed/ok-to-test, needs/ok-to-test

#2238 Fixed broken links - 2024.12
  docs/usage/project-operations.md
  docs/usage/working-with-projects.md
Labels: needs/review, size/xs, needs/ok-to-test
