Repository gardener/dashboard, pull requests merged in 2024-03, with the labels that each got.

#1728 Do not double quote string in yaml config example
  frontend/src/components/GGardenctlConfigExample.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1731 Fixed Issue with Unsupported Preload Type and Unused Preload Links in HTML Document
  frontend/src/plugins/vuetify.js
  frontend/src/sass/materialdesignicons.scss
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test, area/ipcei

#1734 if possible, harmonize non semver compatible image versions
  frontend/__tests__/stores/cloudProfile.spec.js
  frontend/__tests__/utils/index.spec.js
  frontend/src/store/cloudProfile/index.js
  frontend/src/utils/index.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test, area/ipcei

#1751 Fixed GDialog Confirmation can be bypassed using <enter>
  frontend/src/components/dialogs/GDialog.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1750 Filter Non-Kube-Apiserver `AdvertisedAddresses`
  backend/lib/services/shoots.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#1759 [renovate] Ignore major updates for ES modules
  .github/renovate.json5
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test
