Repository gardener/dashboard, pull requests merged in 2024-05, with the labels that each got.

#1842 Comply with DISA STIG V-242415 by mounting secrets as files
  backend/lib/config/gardener.js
  backend/test/config.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/secrets.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/deployment.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
  charts/gardener-dashboard/charts/runtime/templates/dashboard/secret-sessionSecret.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test, area/ipcei

#1856 Support previous session secret, enabling seamless session secret rotation
  backend/__fixtures__/auth.js
  backend/__fixtures__/config.js
  backend/lib/config/gardener.js
  backend/lib/security/index.js
  backend/lib/security/jose.js
  backend/test/security.spec.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/secrets.spec.js.snap
  charts/__tests__/gardener-dashboard/runtime/dashboard/secrets.spec.js
  charts/gardener-dashboard/charts/runtime/templates/dashboard/secret-sessionSecret.yaml
  charts/gardener-dashboard/values.yaml
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1868 Cherry picked fix for vuetify issue #19707
  frontend/src/components/Members/GAccountRoles.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionChips.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/views/GAdministration.vue
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#1857 Update the component name from `dashboard` to `gardener-dashboard`
  .ci/pipeline_definitions
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#1869 Gracefully Handle Session Secret Changes for Seamless User Experience
  backend/lib/security/index.js
  frontend/src/layouts/GDefault.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1867 Some update message improvements
  frontend/__tests__/stores/cloudProfile.spec.js
  frontend/src/components/ShootMessages/GK8sExpirationMessage.vue
  frontend/src/components/ShootMessages/GShootMessages.vue
  frontend/src/components/ShootMessages/GWorkerGroupExpirationMessage.vue
  frontend/src/store/cloudProfile/helper.js
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#1862 Moved Architecture topic to development folder
  .docforge/manifest.yaml
  docs/README.md
  docs/architecture/README.md
  docs/development/architecture.md
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1877 Do not fail if tickets could not be fetched
  frontend/src/components/GTicketsCard.vue
  frontend/src/components/ShootTickets/GTicket.vue
  frontend/src/store/shoot/shoot.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s

#1891 Some PR #1621 review leftovers
  backend/lib/routes/shoots.js
  frontend/__tests__/components/GNewShootDetails.spec.js
  frontend/__tests__/composables/__snapshots__/useShootContext.spec.js.snap
  frontend/__tests__/composables/useShootContext.spec.js
  frontend/__tests__/composables/useShootEditor.spec.js
  frontend/src/components/ControlPlaneHighAvailability/GControlPlaneHighAvailabilityConfiguration.vue
  frontend/src/components/ControlPlaneHighAvailability/GManageControlPlaneHighAvailability.vue
  frontend/src/components/GExpandTransitionGroup.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GTicketsCard.vue
  frontend/src/components/NewShoot/GNewShootDetails.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/components/NewShoot/GNewShootSelectInfrastructure.vue
  frontend/src/components/Secrets/GSelectSecret.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionChips.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictions.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionsConfiguration.vue
  frontend/src/components/ShootAddons/GAddonConfiguration.vue
  frontend/src/components/ShootAddons/GManageAddons.vue
  frontend/src/components/ShootDetails/GShootDetails.vue
  frontend/src/components/ShootDetails/GShootDetailsCard.vue
  frontend/src/components/ShootDns/GDnsConfiguration.vue
  frontend/src/components/ShootDns/GDnsProviderRow.vue
  frontend/src/components/ShootDns/GManageDns.vue
  frontend/src/components/ShootHibernation/GHibernationConfiguration.vue
  frontend/src/components/ShootHibernation/GHibernationScheduleEvent.vue
  frontend/src/components/ShootHibernation/GManageHibernationSchedule.vue
  frontend/src/components/ShootMaintenance/GMaintenanceConfiguration.vue
  frontend/src/components/ShootMaintenance/GMaintenanceTime.vue
  frontend/src/components/ShootWorkers/GMachineImage.vue
  frontend/src/components/ShootWorkers/GManageWorkers.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/components/dialogs/GActionButtonDialog.vue
  frontend/src/composables/useApi/api.js
  frontend/src/composables/useShootAccessRestrictions/index.js
  frontend/src/composables/useShootContext/index.js
  frontend/src/composables/useShootHelper.js
  frontend/src/composables/useShootItem.js
  frontend/src/composables/useShootStatusCredentialRotation.js
  frontend/src/router/guards.js
  frontend/src/router/routes.js
  frontend/src/store/shootContext.js
  frontend/src/utils/index.js
  frontend/src/utils/validators.js
  frontend/src/views/GNewShoot.vue
  frontend/src/views/GNewShootEditor.vue
  frontend/src/views/GNewShootPlaceholder.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl, needs/ok-to-test
