Repository gardener/dashboard, pull requests merged in 2025-05, with the labels that each got.

#2417 Suggest Garden Linux as the node-os in example shoot.yaml
  docs/usage/project-operations.md
  docs/usage/shoot.yaml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2423 [master] No fallback secret details rendering for unknown provider types
  frontend/src/components/Credentials/GCredentialDetailsItemContent.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#2425 [hotfix-1.80] credential details hotfix
  frontend/src/components/Credentials/GCredentialDetailsItemContent.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#2427 Support `Shoot.spec.cloudProfile`
  backend/__fixtures__/secrets.js
  backend/__fixtures__/shoots.js
  backend/__tests__/acceptance/__snapshots__/api.cloudProviderCredentials.spec.js.snap
  backend/__tests__/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/__tests__/acceptance/__snapshots__/io.spec.js.snap
  charts/gardener-dashboard/values.yaml
  docs/operations/access-restrictions.md
  docs/usage/project-operations.md
  docs/usage/shoot.yaml
  frontend/__tests__/composables/__snapshots__/useShootContext.spec.js.snap
  frontend/__tests__/composables/useShootAccessRestrictions.spec.js
  frontend/__tests__/stores/cloudProfile.spec.js
  frontend/src/components/ControlPlaneHighAvailability/GControlPlaneHighAvailabilityTag.vue
  frontend/src/components/Credentials/GSecretDialog.vue
  frontend/src/components/Credentials/GSecretDialogOpenstack.vue
  frontend/src/components/Credentials/GSelectCredential.vue
  frontend/src/components/GCloudProfile.vue
  frontend/src/components/GSelectCloudProfile.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GVendor.vue
  frontend/src/components/NewShoot/GNewShootDetails.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/components/ShootMessages/GK8sExpirationMessage.vue
  frontend/src/components/ShootMessages/GShootMessages.vue
  frontend/src/components/ShootWorkers/GVolumeType.vue
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
  frontend/src/components/ShootWorkers/GWorkerInputGeneric.vue
  frontend/src/composables/useShootAccessRestrictions/index.js
  frontend/src/composables/useShootContext.js
  frontend/src/composables/useShootHelper.js
  frontend/src/composables/useShootItem.js
  frontend/src/composables/useShootSpec.js
  frontend/src/store/cloudProfile/index.js
Labels: needs/review, size/xl, needs/ok-to-test, needs/second-opinion

#2436 Add @klocke-io to CODEOWNERS
  CODEOWNERS
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2435 Fix(ci) exit code 0 issue when check failed
  Makefile
  backend/__tests__/acceptance/__snapshots__/api.shoots.spec.js.snap
  backend/__tests__/acceptance/__snapshots__/io.spec.js.snap
  hack/workspace-run.sh
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#2442 [hotfix] Use static row heigh
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2448 Potential fix for code scanning alert no. 1: Loop bound injection
  backend/lib/services/members/MemberManager.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2447 Potential fix for code scanning alert no. 25: Workflow does not contain permissions
  .github/workflows/dependency-diagrams.yml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2429 Fixed GSecretDialogGeneric [master]
  frontend/__tests__/composables/useSecretContext.spec.js
  frontend/src/components/Credentials/GSecretDialogGeneric.vue
  frontend/src/composables/credential/useSecretContext.js
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#2449 [hotfix-1.80] Fixed GSecretDialogGeneric
  frontend/__tests__/composables/useSecretContext.spec.js
  frontend/src/components/Credentials/GSecretDialogGeneric.vue
  frontend/src/composables/credential/useSecretContext.js
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test

#2452 Cleanup legacy EU access-only sync mechanism and config mapping
  frontend/src/composables/useShootAccessRestrictions/index.js
  frontend/src/store/config.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test
