Repository gardener/dashboard, pull requests merged in 2025-01, with the labels that each got.

#2263 [renovate] Add yarnDedupeHighest postUpdateOptions
  .github/renovate.json5
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#2241 [OpenMFP] use namespace instead of project for fga checks
  backend/lib/openfga/index.js
  backend/lib/openfga/permissionMappings.js
  backend/lib/services/authorization.js
  frontend/src/components/ShootDetails/GShootKubeconfig.vue
Labels: reviewed/lgtm, size/m, reviewed/ok-to-test, needs/ok-to-test, area/ipcei

#2264 Minor bug fixes
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/components/ShootDetails/GShootKubeconfig.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2265 Enh/add make targets
  .ci/check
  .ci/pipeline_definitions
  .ci/verify
  Dockerfile
  Makefile
  hack/workspace-run.sh
Labels: size/m, reviewed/ok-to-test, needs/review, needs/ok-to-test

#2274 Added tests for internal vuetify classes that we rely on for styling
  frontend/__tests__/components/Vuetify.spec.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#1674 Implemented virtual scrolling for Shoot List
  frontend/__tests__/components/Vuetify.spec.js
  frontend/src/components/GDataTableFooter.vue
  frontend/src/store/localStorage.js
  frontend/src/views/GShootList.vue
Labels: size/m, needs/review, needs/ok-to-test, needs/rebase, area/ipcei

#2279 [master] Fix invalid redirect path handling
  backend/lib/security/index.js
  backend/test/security.spec.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test
