Repository gardener/dashboard, pull requests merged in 2025-09, with the labels that each got.

#2589 Considers project tolerations for cloudprofile selection in shoot creation dialogue
  backend/__tests__/acceptance/__snapshots__/api.cloudprofiles.spec.cjs.snap
  backend/lib/cache/index.js
  backend/lib/services/cloudprofiles.js
  frontend/__fixtures__/cloudprofiles.js
  frontend/__tests__/stores/cloudProfile.spec.js
  frontend/__tests__/stores/seed.spec.js
  frontend/src/components/GSelectCloudProfile.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/composables/useShootHelper.js
  frontend/src/store/cloudProfile/index.js
  frontend/src/store/seed.js
  frontend/src/utils/index.js
Labels: reviewed/lgtm, size/xl

#2625 Fixed vuetify set theme upgrade warning
  frontend/src/App.vue
Labels: needs/review, size/xs

#2626 Renovate - Group node updates
  .github/renovate.json5
Labels: needs/review, size/xs

#2628 Renovate/group node updates #2
  .github/renovate.json5
Labels: needs/review, size/xs

#2470 feat: Add support for project titles
  frontend/src/App.vue
  frontend/src/components/GMainNavigation.vue
  frontend/src/components/GProjectTooltip.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/dialogs/GProjectDialog.vue
  frontend/src/components/editable/GEditableText.vue
  frontend/src/components/messages/GRemoveProjectMember.vue
  frontend/src/composables/useProjectContext.js
  frontend/src/composables/useProjectItem.js
  frontend/src/composables/useProjectMetadata/helper.js
  frontend/src/composables/useProjectMetadata/index.js
  frontend/src/composables/useShootMetadata.js
  frontend/src/store/project.js
  frontend/src/store/shoot/helper.js
  frontend/src/utils/annotations.js
  frontend/src/views/GAdministration.vue
  frontend/src/views/GMembers.vue
Labels: reviewed/lgtm, size/l, reviewed/ok-to-test, needs/ok-to-test

#2633 feat: add central serve command
  package.json
Labels: needs/review, size/xs

#2638 fix(frontend): cloudprofilelist filtering by providertype
  frontend/src/components/GSelectCloudProfile.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
Labels: size/s, needs/review

#2641 ci(yarn): disable lifecycle scripts during dependency installation
  .github/workflows/build.yaml
  .github/workflows/dependency-diagrams.yml
  .pnp.cjs
  .yarnrc.yml
  Dockerfile
Labels: reviewed/lgtm, size/xs

#2642 fix(backend): Info endpoint error when retrieving dashboard version information
  backend/eslint.config.cjs
  backend/lib/routes/info.js
Labels: needs/review, size/xs

#2644 fix(frontend) Region Selection - wrong property access
  frontend/src/store/cloudProfile/index.js
Labels: needs/review, size/xs
