Repository gardener/dashboard, pull requests merged in 2025-08, with the labels that each got.

#2539 Add OCI Images Summary job to aggregate matrix results for required status checks
  .github/workflows/build.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#2542 Add merge_group trigger to non-release workflow
  .github/workflows/non-release.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#2533 fix: add dropped sync back from ui to shoot editor
  frontend/src/components/GShootEditor.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/composables/useShootEditor.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#2544 Use GitHub app token
  .github/workflows/cherry-pick.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#2538 Use v-tooltip directive where applicable
  frontend/src/components/ControlPlaneHighAvailability/GManageControlPlaneHighAvailability.vue
  frontend/src/components/Credentials/GCredentialIcon.vue
  frontend/src/components/Credentials/GSharedCredentialIcon.vue
  frontend/src/components/GCollapsibleItems.vue
  frontend/src/components/GCredentialTile.vue
  frontend/src/components/GLinkListTile.vue
  frontend/src/components/GMainNavigation.vue
  frontend/src/components/GMainToolbar.vue
  frontend/src/components/GManageShootCustomFields.vue
  frontend/src/components/GPurposeTag.vue
  frontend/src/components/GRetryOperation.vue
  frontend/src/components/GShootEditor.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/GShootSeedName.vue
  frontend/src/components/GTableColumnSelection.vue
  frontend/src/components/GTerminal.vue
  frontend/src/components/GTerminalSettings.vue
  frontend/src/components/GTerminalShortcut.vue
  frontend/src/components/GTerminalShortcuts.vue
  frontend/src/components/GTerminalTarget.vue
  frontend/src/components/GTimeString.vue
  frontend/src/components/Members/GAccountRoles.vue
  frontend/src/components/Members/GServiceAccountRow.vue
  frontend/src/components/ShootDetails/GCustomFieldsCard.vue
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/components/ShootDetails/GShootInfrastructureCard.vue
  frontend/src/components/ShootVersion/GShootVersionChip.vue
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/components/ShootWorkers/GWorkerGroup.vue
  frontend/src/components/ShootWorkers/GWorkerlessChip.vue
  frontend/src/components/dialogs/GActionButtonDialog.vue
  frontend/src/components/dialogs/GDialog.vue
  frontend/src/components/editable/GEditableAccount.vue
  frontend/src/components/editable/GEditableText.vue
  frontend/src/views/GAdministration.vue
  frontend/src/views/GCredentials.vue
  frontend/src/views/GHome.vue
  frontend/src/views/GMembers.vue
  frontend/src/views/GSettings.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/ok-to-test, size/xl, needs/second-opinion

#2550 Fix build badge
  README.md
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#2578 Make prepare-hotfix workflow reusable
  .github/actions/prepare-hotfix-branch/action.yaml
  .github/actions/prepare-hotfix/action.yaml
  .github/workflows/prepare-hotfix-branch.yaml
Labels: reviewed/lgtm, size/m

#2582 Prepare Hotfix GithubAction: request workflows write permission
  .github/workflows/prepare-hotfix-branch.yaml
Labels: reviewed/lgtm, size/xs

#2583 ci: Cherry-pick enhancements
  .github/actions/cherry-pick/action.yaml
  .github/workflows/cherry-pick-reusable.yaml
Labels: reviewed/lgtm, size/s

#2606 ci: Remove needs/cherry-pick label on successful cherry-pick
  .github/actions/cherry-pick-summary/action.yaml
Labels: reviewed/lgtm, size/xs

#2597 fix IOPS field event binding
  frontend/src/components/ShootWorkers/GVolumeType.vue
Labels: reviewed/lgtm, size/xs, needs/cherry-pick

#2601 Optimized service account column sizing
  frontend/src/components/Members/GAccountRoles.vue
  frontend/src/components/Members/GServiceAccountRow.vue
  frontend/src/components/Members/GUserRow.vue
  frontend/src/components/dialogs/GWebterminalServiceAccountDialog.vue
  frontend/src/utils/index.js
  frontend/src/views/GMembers.vue
Labels: reviewed/lgtm, size/s
