Repository gardener/dashboard, pull requests merged in 2025-03, with the labels that each got.

#2337 Update pipeline_definitions
  .ci/pipeline_definitions
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2351 nit: fix typo in shoot deletion description
  frontend/src/components/ShootDetails/GShootLifecycleCard.vue
Labels: needs/review, size/xs, needs/ok-to-test

#2349 Add PowerDNS support in dashboard
  frontend/__tests__/stores/__snapshots__/credential.spec.js.snap
  frontend/src/assets/powerdns.svg
  frontend/src/components/GVendorIcon.vue
  frontend/src/components/Secrets/GSecretDetailsItemContent.vue
  frontend/src/components/Secrets/GSecretDialogPowerdns.vue
  frontend/src/components/Secrets/GSecretDialogWrapper.vue
  frontend/src/store/gardenerExtension.js
Labels: size/m, needs/review, needs/ok-to-test

#2357 Fixed some issues caused by ProjectPlaceholder
  frontend/src/composables/useTerminalSplitpanes.js
  frontend/src/store/localStorage.js
  frontend/src/views/GProjectPlaceholder.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2368 Fixed request URL path handling
  packages/request/__tests__/client.test.js
  packages/request/lib/Client.js
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2359 extend available data in url expansion for external tools
  charts/gardener-dashboard/values.yaml
  frontend/src/components/ShootDetails/GShootExternalToolsCard.vue
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2361 CodeMirror Fixes
  frontend/src/components/ShootWorkers/GWorkerConfiguration.vue
  frontend/src/composables/useCodemirror/index.js
  frontend/src/composables/useShootEditor.js
  frontend/src/views/GShootItemEditor.vue
Labels: reviewed/lgtm, size/s, needs/ok-to-test

#2291 Improved usage of VDataTableVirtual
  frontend/__tests__/components/Vuetify.spec.js
  frontend/src/components/GDataTableFooter.vue
  frontend/src/components/GScrollContainer.vue
  frontend/src/components/GShootListRow.vue
  frontend/src/components/Members/GServiceAccountRow.vue
  frontend/src/components/Members/GUserRow.vue
  frontend/src/components/Secrets/GSecretDialog.vue
  frontend/src/components/Secrets/GSecretRowDns.vue
  frontend/src/components/Secrets/GSecretRowInfra.vue
  frontend/src/components/ShootAccessRestrictions/GAccessRestrictionChip.vue
  frontend/src/components/icons/GCertifiedKubernetes.vue
  frontend/src/composables/useTwoTableLayout.js
  frontend/src/store/localStorage.js
  frontend/src/views/GMembers.vue
  frontend/src/views/GSecrets.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, size/xl, needs/ok-to-test

#2378 Add glibc to supported libc architectures in .yarnrc.yml
  .yarn/cache/@parcel-watcher-linux-arm64-glibc-npm-2.5.1-fcde7c8778-10c0.zip
  .yarn/cache/@parcel-watcher-linux-x64-glibc-npm-2.5.1-92a895ebe3-10c0.zip
  .yarn/cache/@rollup-rollup-linux-arm64-gnu-npm-4.34.6-16388c222e-10c0.zip
  .yarn/cache/@rollup-rollup-linux-x64-gnu-npm-4.34.6-c869f38311-10c0.zip
  .yarnrc.yml
Labels: reviewed/lgtm, size/xs, needs/ok-to-test
