Repository gardener/dashboard, pull requests merged in 2025-04, with the labels that each got.

#2392 Switch Slack references to Gardener workspace
  README.md
  backend/__fixtures__/config.js
  backend/__tests__/acceptance/__snapshots__/config.spec.js.snap
  charts/__fixtures__/gardener-dashboard.js
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/configmap.spec.js.snap
Labels: kind/enhancement, reviewed/lgtm, size/xs, needs/ok-to-test, area/open-source

#2373 Fix Create Terminal Dialog Issues
  backend/lib/services/shoots.js
  backend/lib/services/terminals/index.js
  frontend/src/components/GTerminalSettings.vue
  frontend/src/components/GTerminalShortcut.vue
  frontend/src/components/GTerminalTarget.vue
  frontend/src/components/ShootDetails/GShootAccessCard.vue
  frontend/src/components/dialogs/GCreateTerminalSessionDialog.vue
  frontend/src/composables/useTerminalConfig.js
  frontend/src/composables/useTerminalSplitpanes.js
  frontend/src/views/GShootItemPlaceholder.vue
Labels: size/l, needs/ok-to-test, needs/second-opinion

#2406 Docker image: fixed issue where `server.(m)js` is not found
  .dockerignore
  Dockerfile
Labels: size/s, needs/review, needs/ok-to-test

#2407 Charts: rename to `server.mjs`
  charts/__tests__/gardener-dashboard/runtime/dashboard/__snapshots__/deployment.spec.js.snap
  charts/gardener-dashboard/charts/runtime/templates/dashboard/deployment.yaml
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2404 Improve error message to make it more descriptive
  frontend/src/utils/errorCodes.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test
