Repository gardener/dashboard, pull requests merged in 2025-02, with the labels that each got.

#2283 Fix promisify warning
  backend/lib/io.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2284 Adapt to OpenID Client v6 API Changes
  .github/renovate.json5
  .pnp.cjs
  .yarn/cache/jose-npm-4.15.9-a725b711d7-4ed4ddf4a0.zip
  .yarn/cache/lru-cache-npm-6.0.0-b4c8668fe1-cb53e58278.zip
  .yarn/cache/oauth4webapi-npm-3.1.4-f7c1f0744d-81e471750f.zip
  .yarn/cache/object-hash-npm-2.2.0-d97a921cc1-1527de8439.zip
  .yarn/cache/oidc-token-hash-npm-5.0.3-7619b94ea8-d0dc055140.zip
  .yarn/cache/openid-client-npm-5.7.1-e8b59fb0f1-6aae649758.zip
  .yarn/cache/openid-client-npm-6.1.7-7ffb12de8b-195d26897b.zip
  .yarn/cache/undici-npm-7.3.0-987a4ccdc7-62c5e33572.zip
  backend/__mocks__/openid-client.js
  backend/lib/auth.js
  backend/lib/middleware.js
  backend/lib/security/index.js
  backend/package.json
  backend/test/acceptance/auth.spec.js
  backend/test/acceptance/security.spec.js
  backend/test/security.spec.js
  charts/gardener-dashboard/values.yaml
  charts/identity/values.yaml
  frontend/src/store/authn/helper.js
  yarn.lock
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#2297 Update broken references in documentation
  docs/development/local-setup.md
  docs/development/process.md
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2292 Re-enable major updates for Jest (renovate)
  .github/renovate.json5
Labels: reviewed/lgtm, size/xs, needs/ok-to-test

#2280 fix setError caller
  frontend/__tests__/components/GLogin.spec.js
  frontend/src/components/GNotify.vue
  frontend/src/components/GRetryOperation.vue
  frontend/src/components/ShootDetails/GShootAdminKubeconfig.vue
  frontend/src/router/routes.js
  frontend/src/store/app.js
  frontend/src/views/GShootItemPlaceholder.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#2331 Fix generic "box icon" tooltip
  frontend/src/components/GShootSubscriptionStatus.vue
  frontend/src/components/GTerminal.vue
  frontend/src/components/GTerminalShortcuts.vue
  frontend/src/components/ShootDetails/GTerminalShortcutsTile.vue
  frontend/src/components/icons/GIconBase.vue
  frontend/src/views/GShootList.vue
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s, needs/ok-to-test

#2330 Do not show header warnings permanently
  frontend/src/store/app.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test
