Repository gardener/dashboard, pull requests merged in 2025-07, with the labels that each got.

#2454 Show cloudprofiles without matching seed
  backend/__tests__/acceptance/__snapshots__/api.cloudprofiles.spec.js.snap
  backend/lib/services/cloudprofiles.js
  diagram/backend-lowlevel-dependency-diagram.html
  frontend/src/components/GSelectCloudProfile.vue
  frontend/src/components/NewShoot/GNewShootInfrastructureDetails.vue
  frontend/src/views/GNewShoot.vue
Labels: reviewed/ok-to-test, size/xl, needs/ok-to-test, needs/second-opinion, area/ipcei

#2502 Add constraint DualStackNodesMigrationReady to wellKnownConditions.
  frontend/src/store/config.js
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs, needs/ok-to-test

#2505 migrate CICD-Pipelines to GitHub-Actions
  .ci/pipeline_definitions
  .ci/verify
  .github/actions/prepare-release/action.yaml
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
  .ocm/base-component.yaml
  hack/verify
Labels: reviewed/lgtm, size/m, needs/ok-to-test

#2510 install dependencies prior to running sast-lint
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, needs/review, size/xs, needs/ok-to-test

#2525 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, needs/review, size/xs

#2528 Add automated cherry-pick GitHub Action workflow
  .github/actions/cherry-pick/action.yaml
  .github/actions/cherry-pick/extract_pr_info.py
  .github/workflows/cherry-pick.yaml
  docs/development/process.md
  hack/cherry-pick-pull.sh
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xl
